#!/usr/bin/env python3
"""Generate the public Python API reference from shipped type stubs.
The generator parses source with the standard library without importing Eqiora,
NumPy, PyTorch, JAX, or Matplotlib, so it cannot initialize the native module or
an optional framework.
"""

from __future__ import annotations

import argparse
import ast
import difflib
import hashlib
import json
import re
import sys
from pathlib import Path
from typing import NamedTuple


ROOT = Path(__file__).resolve().parents[2]
STUB_ROOT = ROOT / "bindings/python/python/eqiora"
MARKDOWN_OUTPUT = ROOT / "docs/python/api.md"
SITE_OUTPUT = ROOT / "docs/site/src/content/docs/reference/python"
GENERATED_NOTICE = "Generated by tools/docs/generate_python_api.py; do not edit."
MARKDOWN_BANNER = f"<!-- {GENERATED_NOTICE} -->"
MDX_BANNER = f"{{/* {GENERATED_NOTICE} */}}"
SOURCE_IMPORT = "import ExactSourceLink from '@components/site/ExactSourceLink.astro';"
RECORD_BYTES = 20_778
RECORD_SHA = "1cf3c73610cab9f11bcadb320aa48f7e63efdf1191a84e6c703900e99b43746d"
EXPECTED_COUNTS = dict(
    zip(
        "modules qualified_exports grouped_declarations classes top_level_function_nodes grouped_functions aliases method_nodes non_dunder_method_nodes dunder_method_nodes visible_class_assignments authoritative_member_summaries signature_only_non_dunder_members canonical_reexports module_exports version_exports".split(),
        map(int, "11 133 114 83 40 30 1 638 501 137 47 0 501 11 7 1".split()),
        strict=True,
    )
)


class ModuleSpec(NamedTuple):
    name: str
    source: Path
    slug: str


def module_spec(slug: str) -> ModuleSpec:
    stem = "__init__" if slug == "eqiora" else slug
    name = "eqiora" if slug == "eqiora" else f"eqiora.{slug}"
    return ModuleSpec(name, Path(f"bindings/python/python/eqiora/{stem}.pyi"), slug)


MODULE_SLUGS = (
    "eqiora geometry meshing fluid trajectory fsi solid matplotlib diff torch jax"
).split()
MODULES = tuple(module_spec(slug) for slug in MODULE_SLUGS)


class Documentation(NamedTuple):
    summary: str
    authority: str


class Declaration(NamedTuple):
    kind: str
    module: str
    name: str
    nodes: list[ast.AST]
    documentation: Documentation


class ImportBinding(NamedTuple):
    canonical: str
    kind: str


class ModuleData(NamedTuple):
    spec: ModuleSpec
    source: str
    tree: ast.Module
    documentation: Documentation
    exports: tuple[str, ...]
    declarations: dict[str, Declaration]
    imports: dict[str, ImportBinding]
    version: ast.AnnAssign | None


class Export(NamedTuple):
    module: str
    name: str
    qualified: str
    canonical: str
    kind: str


AUTHORITY_RE = re.compile(r"(?s)(.+)\n\nAuthority: ``([^`]+)``\.$")
ROLE_RE = re.compile(r":(?:class|func|meth|attr|mod):`([^`]+)`")


def fail(message: str) -> ValueError:
    return ValueError(f"Python API projection refused: {message}")


def parse_documentation(text: str | None, owner: str) -> Documentation:
    if not text:
        raise fail(f"{owner} has no authoritative summary")
    match = AUTHORITY_RE.fullmatch(text)
    if match is None:
        raise fail(f"{owner} does not end in one Authority citation")
    summary = ROLE_RE.sub(r"`\1`", match.group(1).strip()).replace("``", "`")
    authority = match.group(2)
    validate_repository_path(authority.split("::", 1)[0], owner)
    return Documentation(summary=summary, authority=authority)


def validate_repository_path(value: str, owner: str) -> None:
    path = Path(value)
    if (
        not value
        or path.is_absolute()
        or ".." in path.parts
        or any(ord(character) < 32 for character in value)
        or "?" in value
        or "#" in value
    ):
        raise fail(f"{owner} has unsafe authority path {value!r}")
    if not (ROOT / path).is_file():
        raise fail(f"{owner} cites absent authority path {value!r}")


def literal_all(tree: ast.Module, owner: str) -> tuple[str, ...]:
    values: list[ast.expr] = []
    for node in tree.body:
        if not isinstance(node, (ast.Assign, ast.AnnAssign)):
            continue
        targets = node.targets if isinstance(node, ast.Assign) else [node.target]
        if any(
            isinstance(target, ast.Name) and target.id == "__all__"
            for target in targets
        ):
            if node.value is None:
                raise fail(f"{owner} has an empty __all__ assignment")
            values.append(node.value)
    if len(values) != 1:
        raise fail(f"{owner} must have exactly one literal __all__")
    try:
        exported = ast.literal_eval(values[0])
    except (ValueError, TypeError) as error:
        raise fail(f"{owner} __all__ is not literal") from error
    if not isinstance(exported, (list, tuple)) or not all(
        isinstance(name, str) for name in exported
    ):
        raise fail(f"{owner} __all__ is not a string list or tuple")
    if len(exported) != len(set(exported)):
        raise fail(f"{owner} __all__ contains duplicate spellings")
    if any(name.startswith("_") and name != "__version__" for name in exported):
        raise fail(f"{owner} __all__ exposes a private spelling")
    return tuple(exported)


def assignment_names(node: ast.Assign | ast.AnnAssign) -> list[str]:
    targets = [node.target] if isinstance(node, ast.AnnAssign) else node.targets
    return [target.id for target in targets if isinstance(target, ast.Name)]


def module_bindings(tree: ast.Module) -> list[tuple[str, ast.AST]]:
    bindings: list[tuple[str, ast.AST]] = []
    scopes = (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef, ast.Lambda)
    named = (ast.ExceptHandler, ast.MatchAs, ast.MatchStar, ast.MatchMapping)

    def block_nodes(nodes: list[ast.stmt]) -> list[ast.AST]:
        pending, found = list(nodes), []
        while pending:
            node = pending.pop()
            found.append(node)
            if not isinstance(node, scopes):
                pending.extend(ast.iter_child_nodes(node))
        return found

    def visit(node: ast.AST, global_names: set[str] | None) -> None:
        if isinstance(node, ast.Name) and isinstance(node.ctx, (ast.Store, ast.Del)):
            name = node.id
        elif isinstance(node, ast.alias):
            if node.name == "*":
                raise fail("star import makes module bindings ambiguous")
            name = node.asname or node.name.split(".", 1)[0]
        elif isinstance(node, scopes):
            body = [node.body] if isinstance(node, ast.Lambda) else node.body
            if not isinstance(node, ast.Lambda):
                visit(ast.Name(id=node.name, ctx=ast.Store()), global_names)
            for child in ast.iter_child_nodes(node):
                if child not in body:
                    visit(child, global_names)
            if not isinstance(node, ast.Lambda):
                redirected = {
                    name
                    for item in block_nodes(body)
                    if isinstance(item, ast.Global)
                    for name in item.names
                }
                for child in body:
                    visit(child, redirected)
            return
        elif isinstance(
            node, (ast.ListComp, ast.SetComp, ast.DictComp, ast.GeneratorExp)
        ):
            values = (
                [node.key, node.value] if isinstance(node, ast.DictComp) else [node.elt]
            )
            for generator in node.generators:
                values.extend([generator.iter, *generator.ifs])
            for child in values:
                visit(child, global_names)
            return
        elif isinstance(node, named):
            name = node.rest if isinstance(node, ast.MatchMapping) else node.name
        else:
            name = None
        if name and (global_names is None or name in global_names):
            bindings.append((name, node))
        for child in ast.iter_child_nodes(node):
            visit(child, global_names)

    visit(tree, None)
    return bindings


def version_declaration(
    spec: ModuleSpec, tree: ast.Module, exports: tuple[str, ...]
) -> ast.AnnAssign | None:
    nodes = [
        node
        for node in tree.body
        if isinstance(node, ast.AnnAssign) and assignment_names(node) == ["__version__"]
    ]
    bindings = [node for name, node in module_bindings(tree) if name == "__version__"]
    if spec.name != "eqiora" or "__version__" not in exports:
        if bindings or "__version__" in exports:
            raise fail(f"{spec.name} has an unsupported version declaration/export")
        return None
    if len(nodes) != 1 or bindings != [nodes[0].target]:
        raise fail(f"{spec.name} must have exactly one __version__ binding")
    node = nodes[0]
    if node.value is not None:
        raise fail(f"{spec.name} __version__ must be one annotation without a value")
    return node


def overload(node: ast.FunctionDef | ast.AsyncFunctionDef) -> bool:
    return any(
        (isinstance(item, ast.Name) and item.id == "overload")
        or (isinstance(item, ast.Attribute) and item.attr == "overload")
        for item in node.decorator_list
    )


def alias_documentation(
    source: str, node: ast.Assign | ast.AnnAssign, owner: str
) -> Documentation:
    lines = source.splitlines()
    index = node.lineno - 2
    collected: list[str] = []
    while index >= 0 and lines[index].startswith("#:"):
        value = lines[index][2:]
        collected.append(value[1:] if value.startswith(" ") else value)
        index -= 1
    collected.reverse()
    return parse_documentation("\n".join(collected), owner)


def declaration_map(
    spec: ModuleSpec, source: str, tree: ast.Module
) -> dict[str, Declaration]:
    declarations: dict[str, Declaration] = {}
    for node in tree.body:
        if isinstance(node, ast.ClassDef) and not node.name.startswith("_"):
            if node.name in declarations:
                raise fail(f"{spec.name}.{node.name} is declared more than once")
            documentation = parse_documentation(
                ast.get_docstring(node, clean=True), f"{spec.name}.{node.name}"
            )
            declarations[node.name] = Declaration(
                "class", spec.name, node.name, [node], documentation
            )
        elif isinstance(
            node, (ast.FunctionDef, ast.AsyncFunctionDef)
        ) and not node.name.startswith("_"):
            documentation = parse_documentation(
                ast.get_docstring(node, clean=True), f"{spec.name}.{node.name}"
            )
            prior = declarations.get(node.name)
            if prior is None:
                declarations[node.name] = Declaration(
                    "function", spec.name, node.name, [node], documentation
                )
            elif prior.kind != "function" or not (
                overload(node)
                and all(
                    isinstance(item, (ast.FunctionDef, ast.AsyncFunctionDef))
                    and overload(item)
                    for item in prior.nodes
                )
            ):
                raise fail(f"{spec.name}.{node.name} is a duplicate non-overload")
            elif prior.documentation != documentation:
                raise fail(f"{spec.name}.{node.name} overload prose disagrees")
            else:
                prior.nodes.append(node)
        elif isinstance(node, (ast.Assign, ast.AnnAssign)):
            for name in assignment_names(node):
                if name.startswith("_"):
                    continue
                if name in declarations:
                    raise fail(f"{spec.name}.{name} is declared more than once")
                documentation = alias_documentation(source, node, f"{spec.name}.{name}")
                declarations[name] = Declaration(
                    "alias", spec.name, name, [node], documentation
                )
    return declarations


def import_map(tree: ast.Module) -> dict[str, ImportBinding]:
    imports: dict[str, ImportBinding] = {}
    module_names = {spec.name.removeprefix("eqiora.") for spec in MODULES[1:]}
    for node in tree.body:
        if not isinstance(node, ast.ImportFrom) or node.level != 1:
            continue
        base = "eqiora" if node.module is None else f"eqiora.{node.module}"
        for alias in node.names:
            local = alias.asname or alias.name
            if node.module is None and alias.name in module_names:
                imports[local] = ImportBinding(f"eqiora.{alias.name}", "module")
            else:
                imports[local] = ImportBinding(
                    f"{base}.{alias.name}", "canonical-reexport"
                )
    return imports


def validate_module_bindings(module: ModuleData) -> None:
    actual: dict[str, int] = {}
    for name, _ in module_bindings(module.tree):
        if name in module.exports:
            actual[name] = actual.get(name, 0) + 1
    for name in module.exports:
        declaration = module.declarations.get(name)
        if name == "__version__" and module.version is not None:
            expected = 1
        elif declaration is not None:
            expected = len(declaration.nodes)
        else:
            expected = int(name in module.imports)
        observed = actual.get(name, 0)
        if observed != expected:
            raise fail(f"{name} binding multiplicity {observed}/{expected}")


def discover_modules() -> tuple[ModuleData, ...]:
    discovered = set(STUB_ROOT.glob("*.pyi"))
    expected = {ROOT / spec.source for spec in MODULES}
    private = sorted(
        path.relative_to(ROOT).as_posix()
        for path in discovered
        if path.name != "__init__.pyi" and path.stem.startswith("_")
    )
    if private:
        raise fail(f"private stub modules are in the discovered set: {private}")
    missing = sorted(
        path.relative_to(ROOT).as_posix() for path in expected - discovered
    )
    unknown = sorted(
        path.relative_to(ROOT).as_posix() for path in discovered - expected
    )
    if missing or unknown:
        raise fail(f"stub module inventory drift; missing={missing}, unknown={unknown}")

    modules: list[ModuleData] = []
    for spec in MODULES:
        path = ROOT / spec.source
        source = path.read_text(encoding="utf-8")
        if "\r" in source:
            raise fail(f"{spec.source} is not LF-only")
        tree = ast.parse(source, filename=spec.source.as_posix())
        exports = literal_all(tree, spec.name)
        module = ModuleData(
            spec=spec,
            source=source,
            tree=tree,
            documentation=parse_documentation(
                ast.get_docstring(tree, clean=True), spec.name
            ),
            exports=exports,
            declarations=declaration_map(spec, source, tree),
            imports=import_map(tree),
            version=version_declaration(spec, tree, exports),
        )
        validate_module_bindings(module)
        modules.append(module)
    return tuple(modules)


def classify_exports(modules: tuple[ModuleData, ...]) -> tuple[Export, ...]:
    canonical_declarations = {
        f"{declaration.module}.{declaration.name}": declaration
        for module in modules
        for declaration in module.declarations.values()
        if declaration.name in module.exports
    }
    public_modules = {module.spec.name for module in modules}
    exports: list[Export] = []
    for module in modules:
        for name in module.exports:
            qualified = f"{module.spec.name}.{name}"
            if name == "__version__" and module.spec.name == "eqiora":
                export = Export(module.spec.name, name, qualified, qualified, "version")
            elif name in module.declarations:
                export = Export(
                    module.spec.name, name, qualified, qualified, "declaration"
                )
            elif name in module.imports:
                binding = module.imports[name]
                export = Export(
                    module.spec.name, name, qualified, binding.canonical, binding.kind
                )
            else:
                raise fail(f"{qualified} has no declaration or relative import target")
            if export.kind == "module" and export.canonical not in public_modules:
                raise fail(f"{qualified} resolves to unknown module {export.canonical}")
            if (
                export.kind == "canonical-reexport"
                and export.canonical not in canonical_declarations
            ):
                raise fail(
                    f"{qualified} resolves to unknown declaration {export.canonical}"
                )
            exports.append(export)
    return tuple(exports)


def visible_member(name: str) -> bool:
    return not name.startswith("_") or (name.startswith("__") and name.endswith("__"))


def dunder(name: str) -> bool:
    return name.startswith("__") and name.endswith("__")


def validate_inventory(
    modules: tuple[ModuleData, ...], exports: tuple[Export, ...]
) -> dict[str, int]:
    declarations = [
        declaration
        for module in modules
        for name, declaration in module.declarations.items()
        if name in module.exports
    ]
    classes = [
        declaration for declaration in declarations if declaration.kind == "class"
    ]
    functions = [
        declaration for declaration in declarations if declaration.kind == "function"
    ]
    aliases = [
        declaration for declaration in declarations if declaration.kind == "alias"
    ]
    methods = [
        member
        for declaration in classes
        for member in declaration.nodes[0].body
        if isinstance(member, (ast.FunctionDef, ast.AsyncFunctionDef))
        and visible_member(member.name)
    ]
    assignments = [
        member
        for declaration in classes
        for member in declaration.nodes[0].body
        if isinstance(member, (ast.Assign, ast.AnnAssign))
        and (names := assignment_names(member))
        and all(visible_member(name) for name in names)
    ]
    member_summaries = sum(
        ast.get_docstring(member, clean=True) is not None for member in methods
    )
    actual = {
        "modules": len(modules),
        "qualified_exports": len(exports),
        "grouped_declarations": len(declarations),
        "classes": len(classes),
        "top_level_function_nodes": sum(len(item.nodes) for item in functions),
        "grouped_functions": len(functions),
        "aliases": len(aliases),
        "method_nodes": len(methods),
        "non_dunder_method_nodes": sum(not dunder(method.name) for method in methods),
        "dunder_method_nodes": sum(dunder(method.name) for method in methods),
        "visible_class_assignments": len(assignments),
        "authoritative_member_summaries": member_summaries,
        "signature_only_non_dunder_members": sum(
            not dunder(method.name) and ast.get_docstring(method, clean=True) is None
            for method in methods
        ),
        "canonical_reexports": sum(
            item.kind == "canonical-reexport" for item in exports
        ),
        "module_exports": sum(item.kind == "module" for item in exports),
        "version_exports": sum(item.kind == "version" for item in exports),
    }
    if actual != EXPECTED_COUNTS:
        raise fail(
            f"sealed count mismatch; expected={EXPECTED_COUNTS}, actual={actual}"
        )

    ordered = sorted(exports, key=lambda item: item.qualified.encode("utf-8"))
    if len({item.qualified for item in ordered}) != len(ordered):
        raise fail("duplicate qualified export identity")
    records = [
        dict(
            canonical=item.canonical,
            canonical_kind=item.kind,
            module=item.module,
            name=item.name,
            qualified=item.qualified,
        )
        for item in ordered
    ]
    serialization = (
        json.dumps(records, ensure_ascii=False, separators=(",", ":")) + "\n"
    ).encode("utf-8")
    digest = hashlib.sha256(serialization).hexdigest()
    if len(serialization) != RECORD_BYTES or digest != RECORD_SHA:
        raise fail(
            "sealed five-field export record mismatch; "
            f"bytes={len(serialization)}, sha256={digest}"
        )
    return actual


def expression(node: ast.AST | None) -> str:
    return "None" if node is None else ast.unparse(node)


def decorator_lines(decorators: list[ast.expr], *, indent: str = "") -> list[str]:
    return [f"{indent}@{expression(decorator)}" for decorator in decorators]


def function_signature(
    node: ast.FunctionDef | ast.AsyncFunctionDef, *, indent: str = ""
) -> list[str]:
    lines = decorator_lines(node.decorator_list, indent=indent)
    prefix = "async " if isinstance(node, ast.AsyncFunctionDef) else ""
    returns = f" -> {expression(node.returns)}" if node.returns is not None else ""
    lines.append(
        f"{indent}{prefix}def {node.name}({expression(node.args)}){returns}: ..."
    )
    return lines


def assignment_signature(
    node: ast.Assign | ast.AnnAssign, *, indent: str = ""
) -> list[str]:
    if isinstance(node, ast.AnnAssign):
        value = f" = {expression(node.value)}" if node.value is not None else ""
        return [
            f"{indent}{expression(node.target)}: {expression(node.annotation)}{value}"
        ]
    targets = " = ".join(expression(target) for target in node.targets)
    return [f"{indent}{targets} = {expression(node.value)}"]


def declaration_signature(declaration: Declaration) -> list[str]:
    if declaration.kind == "function":
        lines: list[str] = []
        for index, node in enumerate(declaration.nodes):
            if index:
                lines.append("")
            if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                raise AssertionError("function group contains a non-function")
            lines.extend(function_signature(node))
        return lines
    if declaration.kind == "alias":
        node = declaration.nodes[0]
        if not isinstance(node, (ast.Assign, ast.AnnAssign)):
            raise AssertionError("alias group contains a non-assignment")
        return assignment_signature(node)

    node = declaration.nodes[0]
    if not isinstance(node, ast.ClassDef):
        raise AssertionError("class group contains a non-class")
    lines = decorator_lines(node.decorator_list)
    arguments = [expression(base) for base in node.bases]
    arguments.extend(
        f"{keyword.arg}={expression(keyword.value)}"
        for keyword in node.keywords
        if keyword.arg is not None
    )
    suffix = f"({', '.join(arguments)})" if arguments else ""
    lines.append(f"class {node.name}{suffix}:")
    members = 0
    for member in node.body:
        if isinstance(
            member, (ast.FunctionDef, ast.AsyncFunctionDef)
        ) and visible_member(member.name):
            lines.extend(function_signature(member, indent="    "))
            members += 1
        elif isinstance(member, (ast.Assign, ast.AnnAssign)):
            names = assignment_names(member)
            if names and all(visible_member(name) for name in names):
                lines.extend(assignment_signature(member, indent="    "))
                members += 1
    if members == 0:
        lines.append("    ...")
    return lines


def anchor(qualified: str) -> str:
    return "api-" + qualified.replace(".", "-")


def module_route(module: str) -> str:
    spec = next(item for item in MODULES if item.name == module)
    return f"/reference/python/{spec.slug}/"


def mdx_source_link(authority: str) -> str:
    path = authority.split("::", 1)[0]
    return f'<ExactSourceLink path="{path}" kind="blob">{authority}</ExactSourceLink>'


def markdown_source_link(authority: str) -> str:
    path = authority.split("::", 1)[0]
    return f"[`{authority}`](../../{path})"


def mdx_frontmatter(title: str, description: str) -> list[str]:
    return [
        "---",
        f"title: {json.dumps(title, ensure_ascii=False)}",
        f"description: {json.dumps(description, ensure_ascii=False)}",
        "---",
        "",
        SOURCE_IMPORT,
        "",
        MDX_BANNER,
        "",
    ]


def module_lookup(modules: tuple[ModuleData, ...]) -> dict[str, ModuleData]:
    return {module.spec.name: module for module in modules}


def declaration_lookup(modules: tuple[ModuleData, ...]) -> dict[str, Declaration]:
    return {
        f"{declaration.module}.{declaration.name}": declaration
        for module in modules
        for name, declaration in module.declarations.items()
        if name in module.exports
    }


def render_mdx_export(
    export: Export,
    declarations: dict[str, Declaration],
    modules: dict[str, ModuleData],
) -> list[str]:
    lines = [f'<a id="{anchor(export.qualified)}"></a>', "", f"## `{export.name}`", ""]
    if export.kind == "module":
        target = modules[export.canonical]
        lines.extend(
            [
                "**Module export.** This spelling exposes the documented public module "
                f"[`{export.canonical}`]({module_route(export.canonical)}).",
                "",
                target.documentation.summary,
                "",
                f"Authority: {mdx_source_link(target.documentation.authority)}",
                "",
            ]
        )
        return lines
    if export.kind == "canonical-reexport":
        target = declarations[export.canonical]
        lines.extend(
            [
                "**Canonical re-export.** This spelling resolves to "
                f"[`{export.canonical}`]({module_route(target.module)}#{anchor(export.canonical)}).",
                "",
                target.documentation.summary,
                "",
                f"Authority: {mdx_source_link(target.documentation.authority)}",
                "",
            ]
        )
        return lines
    if export.kind == "version":
        version = modules[export.module].version
        assert version is not None
        lines.extend(
            [
                "**Version export.** The current value is intentionally not hard-coded in this generated page.",
                "",
                "```python",
                *assignment_signature(version),
                "```",
                "",
            ]
        )
        return lines

    declaration = declarations[export.canonical]
    lines.extend(
        [
            declaration.documentation.summary,
            "",
            f"Authority: {mdx_source_link(declaration.documentation.authority)}",
            "",
            "```python",
            *declaration_signature(declaration),
            "```",
            "",
        ]
    )
    return lines


def render_mdx_module(
    module: ModuleData,
    exports: tuple[Export, ...],
    modules: dict[str, ModuleData],
    declarations: dict[str, Declaration],
) -> str:
    owned = [item for item in exports if item.module == module.spec.name]
    lines = mdx_frontmatter(
        module.spec.name,
        f"Public signatures and source-traced summaries for {module.spec.name}.",
    )
    lines.extend(
        [
            "[← Python API index](/reference/python/)",
            "",
            module.documentation.summary,
            "",
            f"Module authority: {mdx_source_link(module.documentation.authority)}",
            "",
            f"Shipped stub: {mdx_source_link(module.spec.source.as_posix())}",
            "",
            f"This module publishes **{len(owned)}** literal `__all__` spellings. "
            "Member entries below are exact signatures under documented owning types; "
            "they do not imply member-level behavioral prose.",
            "",
        ]
    )
    for export in owned:
        lines.extend(render_mdx_export(export, declarations, modules))
    return "\n".join(lines).rstrip() + "\n"


def render_mdx_index(modules: tuple[ModuleData, ...], counts: dict[str, int]) -> str:
    lines = mdx_frontmatter(
        "Python API",
        "Complete public Python surface and signature reference for one exact source commit.",
    )
    lines.extend(
        [
            "This is the complete public **surface/signature reference** generated from the shipped type stubs. "
            "It parses source without importing Eqiora or optional frameworks.",
            "",
            "> API presence is neither capability evidence nor maturity. Behavioral guidance remains bounded by each cited source and the linked evidence catalog.",
            "",
            "## Coverage",
            "",
            "| Surface | Exact count | Documentation boundary |",
            "| --- | ---: | --- |",
            f"| Public modules | {counts['modules']} | {counts['modules']}/{counts['modules']} reviewed module summaries |",
            f"| Literal public spellings | {counts['qualified_exports']} | Every spelling is direct, a module/version export, or linked to its canonical target |",
            f"| Canonical grouped declarations | {counts['grouped_declarations']} | {counts['grouped_declarations']}/{counts['grouped_declarations']} reviewed declaration summaries |",
            f"| Public classes | {counts['classes']} | Owning-type summaries and exact signatures |",
            f"| Top-level function syntax nodes | {counts['top_level_function_nodes']} | {counts['grouped_functions']} overload-grouped function names |",
            f"| Non-dunder methods | {counts['non_dunder_method_nodes']} | **{counts['authoritative_member_summaries']} authoritative member summaries; {counts['signature_only_non_dunder_members']} signature-only under documented owning types** |",
            f"| Dunder methods | {counts['dunder_method_nodes']} | Exact signatures; no individual narrative required |",
            f"| Visible class assignments | {counts['visible_class_assignments']} | Exact typed/value signatures; no individual narrative required |",
            "",
            "The generator does not infer units, defaults, error behavior, ordering, complexity, backend support, portability, stability, or side effects from names and types.",
            "",
            "## Modules",
            "",
            "| Module | Summary |",
            "| --- | --- |",
        ]
    )
    for module in modules:
        lines.append(
            f"| [`{module.spec.name}`]({module_route(module.spec.name)}) | "
            f"{module.documentation.summary} |"
        )
    lines.extend(
        [
            "",
            "## Regenerate",
            "",
            "```console",
            "python3 tools/docs/generate_python_api.py",
            "python3 tools/docs/generate_python_api.py --check",
            "```",
            "",
        ]
    )
    return "\n".join(lines).rstrip() + "\n"


def render_markdown_export(
    export: Export,
    declarations: dict[str, Declaration],
    modules: dict[str, ModuleData],
) -> list[str]:
    lines = [
        f'<a id="{anchor(export.qualified)}"></a>',
        "",
        f"### `{export.qualified}`",
        "",
    ]
    if export.kind == "module":
        target = modules[export.canonical]
        lines.extend(
            [
                f"**Module export.** Continue to [`{export.canonical}`](#module-{export.canonical.replace('.', '-')}).",
                "",
                target.documentation.summary,
                "",
                f"Authority: {markdown_source_link(target.documentation.authority)}",
                "",
            ]
        )
        return lines
    if export.kind == "canonical-reexport":
        target = declarations[export.canonical]
        lines.extend(
            [
                f"**Canonical re-export.** This spelling resolves to [`{export.canonical}`](#{anchor(export.canonical)}).",
                "",
                target.documentation.summary,
                "",
                f"Authority: {markdown_source_link(target.documentation.authority)}",
                "",
            ]
        )
        return lines
    if export.kind == "version":
        version = modules[export.module].version
        assert version is not None
        lines.extend(
            [
                "**Version export.** The current value is intentionally not hard-coded here.",
                "",
                "```python",
                *assignment_signature(version),
                "```",
                "",
            ]
        )
        return lines
    declaration = declarations[export.canonical]
    lines.extend(
        [
            declaration.documentation.summary,
            "",
            f"Authority: {markdown_source_link(declaration.documentation.authority)}",
            "",
            "```python",
            *declaration_signature(declaration),
            "```",
            "",
        ]
    )
    return lines


def render_markdown(
    module_data: tuple[ModuleData, ...],
    exports: tuple[Export, ...],
    counts: dict[str, int],
) -> str:
    modules = module_lookup(module_data)
    declarations = declaration_lookup(module_data)
    lines = [
        MARKDOWN_BANNER,
        "",
        "# Eqiora Python API",
        "",
        "This complete public surface/signature reference is generated deterministically from the shipped type stubs. It does not import Eqiora or an optional framework.",
        "",
        f"API presence is neither capability evidence nor maturity. All {counts['modules']} module summaries and all {counts['grouped_declarations']} canonical declaration summaries are source-traced; non-dunder member coverage remains **{counts['authoritative_member_summaries']} authoritative summaries and {counts['signature_only_non_dunder_members']} signature-only entries under documented owning types**.",
        "",
        f"Inventory: {counts['modules']} modules, {counts['qualified_exports']} literal public spellings, {counts['grouped_declarations']} canonical grouped declarations, {counts['method_nodes']} visible method signatures ({counts['non_dunder_method_nodes']} non-dunder and {counts['dunder_method_nodes']} dunder), and {counts['visible_class_assignments']} visible class assignments.",
        "",
        "Regenerate with:",
        "",
        "```console",
        "python3 tools/docs/generate_python_api.py",
        "python3 tools/docs/generate_python_api.py --check",
        "```",
        "",
    ]
    for module in module_data:
        lines.extend(
            [
                f'<a id="module-{module.spec.name.replace(".", "-")}"></a>',
                "",
                f"## `{module.spec.name}`",
                "",
                module.documentation.summary,
                "",
                f"Module authority: {markdown_source_link(module.documentation.authority)}",
                "",
                f"Shipped stub: [`{module.spec.source.as_posix()}`](../../{module.spec.source.as_posix()})",
                "",
            ]
        )
        for export in exports:
            if export.module == module.spec.name:
                lines.extend(render_markdown_export(export, declarations, modules))
    return "\n".join(lines).rstrip() + "\n"


def render_outputs() -> dict[Path, str]:
    module_data = discover_modules()
    exports = classify_exports(module_data)
    counts = validate_inventory(module_data, exports)
    modules = module_lookup(module_data)
    declarations = declaration_lookup(module_data)
    outputs = {
        MARKDOWN_OUTPUT: render_markdown(module_data, exports, counts),
        SITE_OUTPUT / "index.mdx": render_mdx_index(module_data, counts),
    }
    for module in module_data:
        outputs[SITE_OUTPUT / f"{module.spec.slug}.mdx"] = render_mdx_module(
            module, exports, modules, declarations
        )
    if len(outputs) != 13:
        raise fail(f"expected 13 generated outputs, got {len(outputs)}")
    for path, rendered in outputs.items():
        encoded = rendered.encode("utf-8")
        if b"\r" in encoded or not encoded.endswith(b"\n"):
            raise fail(f"{path.relative_to(ROOT)} is not canonical UTF-8/LF")
        if "/blob/main/" in rendered or "/tree/main/" in rendered:
            raise fail(f"{path.relative_to(ROOT)} contains a branch source link")
        if "_eqiora" in rendered:
            raise fail(f"{path.relative_to(ROOT)} leaks the private native module")
    return outputs


def check(outputs: dict[Path, str]) -> int:
    failures = 0
    for path, expected in outputs.items():
        relative = path.relative_to(ROOT)
        if not path.is_file():
            print(f"{relative} is missing", file=sys.stderr)
            failures += 1
            continue
        actual = path.read_text(encoding="utf-8")
        if actual == expected:
            print(f"{relative} is current")
            continue
        diff = difflib.unified_diff(
            actual.splitlines(),
            expected.splitlines(),
            fromfile=relative.as_posix(),
            tofile="generated",
            lineterm="",
        )
        print("\n".join(diff), file=sys.stderr)
        failures += 1
    return 1 if failures else 0


def write(outputs: dict[Path, str]) -> int:
    for path, rendered in outputs.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(rendered, encoding="utf-8", newline="\n")
        print(f"wrote {path.relative_to(ROOT)}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail without writing when any Markdown/MDX projection differs",
    )
    arguments = parser.parse_args()
    try:
        outputs = render_outputs()
    except (OSError, SyntaxError, ValueError) as error:
        print(str(error), file=sys.stderr)
        return 1
    return check(outputs) if arguments.check else write(outputs)


if __name__ == "__main__":
    raise SystemExit(main())
