# Generated by Eqiora Studio from an accepted authored CAD graph.
# Length arguments are coherent-SI metres.
import eqiora

geometry_graph = eqiora.geometry.GeometryGraph()
authored_graph = geometry_graph.rectangle_extrusion(
    x_bounds=(-0.04, 0.04),
    y_bounds=(-0.025, 0.025),
    plane_z=0.0,
    depth=0.02,
    modeling_tolerance=1e-10,
)
authored_graph = geometry_graph.circular_through_cut(
    authored_graph,
    center=(0.02, 0.0),
    radius=0.008,
    boolean_tolerance=1e-9,
)

_expected_graph_digest = (
    "00acb9494fc7dea8f1f2500d1316cb3315130a965a24179b3eb1b10345058b47"
)
if authored_graph.graph_digest != _expected_graph_digest:
    raise RuntimeError("Eqiora authored CAD graph digest mismatch after reconstruction")
