use super::*;

fn library_fixture() -> Fixture {
    let fixture = Fixture::new();
    fs::write(
        fixture.root.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"eqiora-numerics\"\nversion = \"0.0.0\"\n",
    )
    .unwrap();
    fs::write(
        fixture.root.join("eqiora-numerics/src/lib.rs"),
        r#"
#[cfg(test)]
mod private_parent {
    mod private_child {
        #[test]
        fn registered_evidence() {
            use std::io::Write as _;
            let mut marker = std::fs::OpenOptions::new()
                .create(true)
                .append(true)
                .open("selected.marker")
                .unwrap();
            writeln!(marker, "selected").unwrap();
        }

        #[test]
        fn registered_evidence_extra() {
            std::fs::write("substring.marker", "substring also ran\n").unwrap();
        }

        #[test]
        #[ignore = "registered evidence must reject ignored tests"]
        fn ignored_evidence() {
            std::fs::write("ignored.marker", "ignored test ran\n").unwrap();
        }

        #[test]
        fn failing_evidence() {
            panic!("frozen private oracle failure");
        }
    }
}
"#,
    )
    .unwrap();
    fixture
}

fn valid_library_manifest() -> &'static str {
    r#"
id = "area.case"
status = "verified"
reference_kind = "compiler-contract"
capabilities = ["private-library-oracle"]

[evidence]
runner = "cargo-library-test"
package = "eqiora-numerics"
test = "private_parent::private_child::registered_evidence"
features = ["one", "two"]
table = "expected/evidence.csv"
"#
}

fn library_target_with(test: &str, features: &[&str]) -> EvidenceTarget {
    let features = features
        .iter()
        .map(|feature| format!("\"{feature}\""))
        .collect::<Vec<_>>()
        .join(", ");
    toml::from_str(&format!(
        "runner = \"cargo-library-test\"\npackage = \"eqiora-numerics\"\ntest = \"{test}\"\nfeatures = [{features}]\n"
    ))
    .unwrap()
}

fn bin_only_fixture() -> Fixture {
    let fixture = Fixture::new();
    fs::write(
        fixture.root.join("Cargo.toml"),
        "[workspace]\nmembers = [\"bin-only\"]\nresolver = \"2\"\n",
    )
    .unwrap();
    fs::create_dir_all(fixture.root.join("bin-only/src")).unwrap();
    fs::write(
        fixture.root.join("bin-only/Cargo.toml"),
        "[package]\nname = \"bin-only\"\nversion = \"0.0.0\"\nedition = \"2024\"\n",
    )
    .unwrap();
    fs::write(fixture.root.join("bin-only/src/main.rs"), "fn main() {}\n").unwrap();
    fixture.write_manifest(
        r#"
id = "area.case"
status = "verified"
reference_kind = "compiler-contract"
capabilities = ["private-library-oracle"]

[evidence]
runner = "cargo-library-test"
package = "bin-only"
test = "private_parent::private_child::registered_evidence"
"#,
    );
    fixture
}

fn mismatched_package_directory_fixture() -> Fixture {
    let fixture = Fixture::new();
    fs::write(
        fixture.root.join("Cargo.toml"),
        "[workspace]\nmembers = [\"selected-directory\", \"selected-package\"]\nresolver = \"2\"\n",
    )
    .unwrap();
    fs::write(
        fixture.root.join("Cargo.lock"),
        "# This file is automatically @generated by Cargo.\n# It is not intended for manual editing.\nversion = 4\n\n[[package]]\nname = \"selected-package\"\nversion = \"0.0.0\"\ndependencies = [\n \"selected-package-dependency\",\n]\n\n[[package]]\nname = \"selected-package-dependency\"\nversion = \"0.0.0\"\n",
    )
    .unwrap();
    fs::create_dir_all(fixture.root.join("selected-directory/src")).unwrap();
    fs::create_dir_all(fixture.root.join("selected-package/src")).unwrap();
    fs::write(
        fixture.root.join("selected-directory/Cargo.toml"),
        "[package]\nname = \"selected-package\"\nversion = \"0.0.0\"\nedition = \"2024\"\n\n[dependencies]\nselected-package-dependency = { path = \"../selected-package\" }\n",
    )
    .unwrap();
    fs::write(
        fixture.root.join("selected-package/Cargo.toml"),
        "[package]\nname = \"selected-package-dependency\"\nversion = \"0.0.0\"\nedition = \"2024\"\n",
    )
    .unwrap();
    fs::write(
        fixture.root.join("selected-directory/src/lib.rs"),
        r#"
pub fn dependency_value() -> u8 {
    selected_package_dependency::value()
}

#[cfg(test)]
mod private_parent {
    mod private_child {
        #[test]
        fn registered_evidence() {
            std::fs::write("selected-package.marker", "selected package\n").unwrap();
        }
    }
}
"#,
    )
    .unwrap();
    fs::write(
        fixture.root.join("selected-package/src/lib.rs"),
        r#"
pub fn value() -> u8 {
    7
}

#[cfg(test)]
mod private_parent {
    mod private_child {
        #[test]
        fn registered_evidence() {
            std::fs::write("dependency.marker", "dependency package\n").unwrap();
        }
    }
}
"#,
    )
    .unwrap();
    fixture.write_manifest(
        r#"
id = "area.case"
status = "verified"
reference_kind = "compiler-contract"
capabilities = ["private-library-oracle"]

[evidence]
runner = "cargo-library-test"
package = "selected-package"
test = "private_parent::private_child::registered_evidence"
"#,
    );
    fixture
}

#[test]
fn legacy_python_target_serialization_remains_exact() {
    let python = EvidenceTarget::PythonInstalledWheel(PythonInstalledWheelEvidenceTarget {
        runner: PythonEvidenceRunner::PythonInstalledWheel,
        script: "tools/ci/python_evidence.py".to_owned(),
        environment: EvidenceEnvironment::HostCpu,
    });
    assert_eq!(
        serde_json::to_value(python).unwrap(),
        serde_json::json!({
            "runner": "python-installed-wheel",
            "script": "tools/ci/python_evidence.py"
        })
    );
}

#[test]
fn reserved_internal_prefix_cannot_select_library_evidence_without_the_runner() {
    let explicit = library_target_with("a::b", &[]);
    assert!(matches!(
        explicit,
        EvidenceTarget::Cargo(CargoEvidenceTarget { ref test, .. }) if test == "lib::a::b"
    ));

    let bypass = "package = \"eqiora-numerics\"\ntest = \"lib::a::b\"\n";
    assert!(
        toml::from_str::<EvidenceTarget>(bypass).is_err(),
        "the reserved internal prefix must not replace explicit `runner = \"cargo-library-test\"`"
    );

    let fixture = library_fixture();
    fixture.write_manifest(
        &valid_library_manifest()
            .replace("runner = \"cargo-library-test\"\n", "")
            .replace(
                "private_parent::private_child::registered_evidence",
                "lib::a::b",
            ),
    );
    let error = load_repository_with_targets(&fixture.root, &targets()).unwrap_err();
    assert!(
        error.contains("cargo-library-test") || error.contains("integration-test target"),
        "{error}"
    );
}

#[test]
fn library_manifest_rejects_a_workspace_package_without_a_library_target() {
    let fixture = bin_only_fixture();
    let runner = FakeRunner::new([]);
    let report = execute(
        &fixture.root,
        &Request::new(CommandKind::Check, Vec::new(), ExecutionPolicy::FailFast),
        &runner,
    );

    assert!(!report.success, "{report:?}");
    assert!(report.cases.is_empty(), "{report:?}");
    assert!(
        report
            .errors
            .iter()
            .any(|error| error.contains("bin-only") && error.contains("library target")),
        "{report:?}"
    );
    assert!(runner.groups().is_empty());
    assert!(runner.targets().is_empty());
}

#[test]
fn system_runner_selects_the_exact_package_when_its_directory_name_differs() {
    let fixture = mismatched_package_directory_fixture();
    let report = execute(
        &fixture.root,
        &Request::new(CommandKind::Run, Vec::new(), ExecutionPolicy::FailFast),
        &SystemEvidenceRunner::from_environment(),
    );

    assert!(report.success, "{report:?}");
    assert_eq!(report.cases[0].outcome, Outcome::Passed);
    assert_eq!(
        fs::read_to_string(fixture.root.join("selected-package.marker")).unwrap(),
        "selected package\n"
    );
    assert!(!fixture.root.join("dependency.marker").exists());
}

#[test]
fn manifest_shape_is_closed_and_preserves_legacy_shapes() {
    let fixture = library_fixture();
    fixture.write_manifest(valid_library_manifest());
    let contracts = load_repository_with_targets(&fixture.root, &targets()).unwrap();
    let library = contracts[0].evidence.as_ref().unwrap();
    assert!(matches!(
        library,
        EvidenceTarget::Cargo(CargoEvidenceTarget { package, test, .. })
            if package == "eqiora-numerics"
                && test == "lib::private_parent::private_child::registered_evidence"
    ));
    assert_eq!(library.runner_kind(), RunnerKind::Cargo);
    assert_eq!(library.environment(), EvidenceEnvironment::HostCpu);
    assert_eq!(
        library.human_label(),
        "cargo-library-test/eqiora-numerics/private_parent::private_child::registered_evidence"
    );
    assert_eq!(
        serde_json::to_value(library).unwrap(),
        serde_json::json!({
            "runner": "cargo-library-test",
            "package": "eqiora-numerics",
            "test": "private_parent::private_child::registered_evidence",
            "features": ["one", "two"],
            "table": "expected/evidence.csv"
        })
    );

    let index = build_capability_evidence_index(contracts, None);
    assert!(index.success);
    assert_eq!(
        index.render_human(),
        "private-library-oracle -> area.case [verified; compiler-contract; cargo-library-test/eqiora-numerics/private_parent::private_child::registered_evidence]\nindexed 1 capability evidence entry\n"
    );

    for field in [
        "command = \"sh -c anything\"",
        "args = [\"--arbitrary\"]",
        "source_path = \"src/lib.rs\"",
        "path = \"src/lib.rs\"",
        "target = \"lib\"",
        "tests = [\"private_parent::private_child::registered_evidence\"]",
        "test_args = [\"--exact\"]",
    ] {
        assert!(
            toml::from_str::<CaseManifest>(&format!("{}\n{field}\n", valid_library_manifest()))
                .is_err(),
            "library evidence unexpectedly accepted `{field}`"
        );
    }
    for runner in ["cargo", "cargo-library", "cargo-library-tests", "command"] {
        assert!(
            toml::from_str::<CaseManifest>(
                &valid_library_manifest().replace("cargo-library-test", runner)
            )
            .is_err(),
            "library evidence unexpectedly accepted runner `{runner}`"
        );
    }

    let without_runner = valid_library_manifest().replace("runner = \"cargo-library-test\"\n", "");
    fixture.write_manifest(&without_runner);
    let error = load_repository_with_targets(&fixture.root, &targets()).unwrap_err();
    assert!(error.contains("missing integration-test target"), "{error}");

    for required in ["package", "test"] {
        let source = valid_library_manifest()
            .lines()
            .filter(|line| !line.starts_with(&format!("{required} = ")))
            .collect::<Vec<_>>()
            .join("\n");
        assert!(
            toml::from_str::<CaseManifest>(&source).is_err(),
            "library evidence unexpectedly accepted a missing `{required}`"
        );
    }
}

#[test]
fn selector_grammar_is_exact_and_fully_qualified() {
    let fixture = library_fixture();
    for valid in ["a::b", "a_b::c9", "one::two_three::four4"] {
        fixture.write_manifest(
            &valid_library_manifest()
                .replace("private_parent::private_child::registered_evidence", valid),
        );
        load_repository_with_targets(&fixture.root, &targets()).unwrap();
    }

    for invalid in [
        "registered_evidence",
        "A::b",
        "a::B",
        "a-b::c",
        "1a::b",
        "_a::b",
        "a::",
        "a::::b",
        "a:b",
        "a::b.c",
        "a::b*",
        "a::b::9c",
    ] {
        fixture.write_manifest(&valid_library_manifest().replace(
            "private_parent::private_child::registered_evidence",
            invalid,
        ));
        let error = load_repository_with_targets(&fixture.root, &targets()).unwrap_err();
        assert!(
            error.contains("library evidence test")
                && error.contains("exact fully qualified lowercase Rust test name"),
            "selector `{invalid}` produced unexpected error: {error}"
        );
    }

    fixture.write_manifest(&valid_library_manifest().replace(
        "features = [\"one\", \"two\"]",
        "features = [\"one\", \"one\"]",
    ));
    let error = load_repository_with_targets(&fixture.root, &targets()).unwrap_err();
    assert!(error.contains("repeats evidence feature `one`"), "{error}");
}

#[test]
fn execution_identity_includes_shape_exact_test_and_normalized_features() {
    let first = library_target_with("one::registered_evidence", &["one", "two"]);
    let reordered = library_target_with("one::registered_evidence", &["two", "one"]);
    let second = library_target_with("two::registered_evidence", &["one", "two"]);
    let integration = EvidenceTarget::Cargo(CargoEvidenceTarget {
        package: "eqiora-numerics".to_owned(),
        test: "one_registered_evidence".to_owned(),
        features: vec!["one".to_owned(), "two".to_owned()],
        table: None,
        environment: EvidenceEnvironment::HostCpu,
    });

    let first_key = ExecutionKey::from_target(&first);
    assert!(matches!(
        &first,
        EvidenceTarget::Cargo(CargoEvidenceTarget { test, .. })
            if test == "lib::one::registered_evidence"
    ));
    assert_eq!(first_key, ExecutionKey::from_target(&reordered));
    assert_ne!(first_key, ExecutionKey::from_target(&second));
    assert_ne!(first_key, ExecutionKey::from_target(&integration));
    assert!(first_key.label().starts_with("cargo-library-test package="));
}

fn runnable_library_manifest(test: &str, environment: EvidenceEnvironment) -> String {
    let environment = if environment == EvidenceEnvironment::HostCpu {
        String::new()
    } else {
        format!("environment = \"{}\"\n", environment.as_str())
    };
    format!(
        r#"
id = "area.case"
status = "verified"
reference_kind = "compiler-contract"
capabilities = ["private-library-oracle"]

[evidence]
runner = "cargo-library-test"
package = "eqiora-numerics"
test = "{test}"
{environment}"#
    )
}

fn diagnostic_library_manifest(test: &str, environment: EvidenceEnvironment) -> String {
    let environment = if environment == EvidenceEnvironment::HostCpu {
        String::new()
    } else {
        format!("environment = \"{}\"\n", environment.as_str())
    };
    format!(
        r#"
id = "area.case"
status = "verified"
reference_kind = "compiler-contract"
capabilities = ["private-library-oracle"]

[evidence]
runner = "cargo-library-test"
package = "eqiora-numerics"
test = "{test}"
features = ["zeta", "alpha"]
{environment}"#
    )
}

#[test]
fn preflight_rejections_retain_the_exact_reproduction_command() {
    let fixture = library_fixture();
    fs::write(
        fixture.root.join("eqiora-numerics/Cargo.toml"),
        "[package]\nname = \"eqiora-numerics\"\nversion = \"0.0.0\"\nedition = \"2024\"\n\n[features]\nalpha = []\nzeta = []\n",
    )
    .unwrap();
    let runner = SystemEvidenceRunner::from_environment();
    let request = Request::new(CommandKind::Run, Vec::new(), ExecutionPolicy::FailFast);

    for (test, environment, physical_flag) in [
        (
            "private_parent::private_child::missing_evidence",
            EvidenceEnvironment::HostCpu,
            "",
        ),
        (
            "private_parent::private_child::renamed_evidence",
            EvidenceEnvironment::HostCpu,
            "",
        ),
        (
            "private_parent::private_child::ignored_evidence",
            EvidenceEnvironment::HostCpu,
            "",
        ),
        (
            "private_parent::private_child::registered_evidence",
            EvidenceEnvironment::PhysicalMpiCuda,
            " --ignored",
        ),
    ] {
        fixture.write_manifest(&diagnostic_library_manifest(test, environment));
        let report = execute(&fixture.root, &request, &runner);
        assert!(!report.success, "{test}: {report:?}");
        assert_eq!(report.cases[0].outcome, Outcome::Failed);
        let case = &report.cases[0];
        let retained = format!(
            "{}\n{}",
            case.message.as_deref().unwrap_or_default(),
            case.stderr.as_deref().unwrap_or_default()
        );
        let command = format!(
            "cargo test --locked -p eqiora-numerics --lib --features alpha,zeta {test} -- --exact{physical_flag}"
        );
        assert!(
            retained.contains(&command),
            "preflight rejection did not retain `{command}`:\n{retained}"
        );
    }
}

#[test]
fn system_runner_executes_one_exact_private_test_and_fails_closed_preflight() {
    let fixture = library_fixture();
    assert!(
        !fs::read_to_string(fixture.root.join("eqiora-numerics/Cargo.toml"))
            .unwrap()
            .contains("[[test]]")
    );
    let runner = SystemEvidenceRunner::from_environment();
    let request = Request::new(CommandKind::Run, Vec::new(), ExecutionPolicy::FailFast);

    fixture.write_manifest(&runnable_library_manifest(
        "private_parent::private_child::registered_evidence",
        EvidenceEnvironment::HostCpu,
    ));
    let report = execute(&fixture.root, &request, &runner);
    assert!(report.success, "{report:?}");
    assert_eq!(report.cases[0].outcome, Outcome::Passed);
    assert_eq!(
        fs::read_to_string(fixture.root.join("selected.marker")).unwrap(),
        "selected\n"
    );
    assert!(!fixture.root.join("substring.marker").exists());

    fs::remove_file(fixture.root.join("selected.marker")).unwrap();
    for (test, environment, expected) in [
        (
            "private_parent::private_child::renamed_evidence",
            EvidenceEnvironment::HostCpu,
            "is missing from the host-cpu libtest inventory",
        ),
        (
            "private_child::registered_evidence",
            EvidenceEnvironment::HostCpu,
            "is missing from the host-cpu libtest inventory",
        ),
        (
            "private_parent::private_child::ignored_evidence",
            EvidenceEnvironment::HostCpu,
            "is ignored but host-cpu library evidence requires a non-ignored test",
        ),
        (
            "private_parent::private_child::registered_evidence",
            EvidenceEnvironment::PhysicalMpiCuda,
            "is not ignored but physical-mpi-cuda library evidence requires an ignored test",
        ),
    ] {
        fixture.write_manifest(&runnable_library_manifest(test, environment));
        let report = execute(&fixture.root, &request, &runner);
        assert!(!report.success, "{test}: {report:?}");
        assert_eq!(report.cases[0].outcome, Outcome::Failed);
        assert!(
            report.cases[0]
                .message
                .as_deref()
                .is_some_and(|message| message.contains(expected)),
            "{test}: {report:?}"
        );
        assert!(!fixture.root.join("selected.marker").exists());
        assert!(!fixture.root.join("substring.marker").exists());
        assert!(!fixture.root.join("ignored.marker").exists());
    }

    fixture.write_manifest(&runnable_library_manifest(
        "private_parent::private_child::ignored_evidence",
        EvidenceEnvironment::PhysicalMpiCuda,
    ));
    let report = execute(&fixture.root, &request, &runner);
    assert!(report.success, "{report:?}");
    assert_eq!(report.cases[0].outcome, Outcome::Passed);
    assert_eq!(
        fs::read_to_string(fixture.root.join("ignored.marker")).unwrap(),
        "ignored test ran\n"
    );
    assert!(!fixture.root.join("selected.marker").exists());
    assert!(!fixture.root.join("substring.marker").exists());

    fixture.write_manifest(&runnable_library_manifest(
        "private_parent::private_child::failing_evidence",
        EvidenceEnvironment::HostCpu,
    ));
    let report = execute(&fixture.root, &request, &runner);
    assert!(!report.success, "{report:?}");
    let stderr = report.cases[0].stderr.as_deref().unwrap_or_default();
    assert!(stderr.contains("frozen private oracle failure"), "{stderr}");
    assert!(
        stderr.contains(
            "error: test failed, to rerun pass `cargo test --locked -p eqiora-numerics --lib private_parent::private_child::failing_evidence -- --exact`"
        ),
        "{stderr}"
    );
}

#[test]
fn selectors_share_one_library_build_but_not_an_integration_build() {
    let first = library_target_with("private_parent::first", &["one", "two"]);
    let second = library_target_with("private_parent::second", &["two", "one"]);
    let integration = named_cargo_target("eqiora-numerics", "evidence_test", &["one", "two"]);
    let runner = FakeRunner::for_targets([
        (first.clone(), output(0, "library-first")),
        (second.clone(), output(0, "library-second")),
        (integration.clone(), output(0, "integration")),
    ]);
    let reports = execute_selected(
        Path::new("."),
        vec![
            contract_with_target("a", first.clone()),
            contract_with_target("b", second.clone()),
            contract_with_target("c", integration.clone()),
        ],
        &Request::new(CommandKind::Run, Vec::new(), ExecutionPolicy::KeepGoing)
            .for_runner_kind(RunnerKind::Cargo),
        &runner,
    );

    assert!(reports.iter().all(|case| case.outcome == Outcome::Passed));
    assert_eq!(
        runner.targets(),
        [first.clone(), second.clone(), integration.clone()]
    );
    let groups = runner.groups();
    assert_eq!(groups.len(), 2, "{groups:?}");
    assert!(
        groups
            .iter()
            .any(|group| group == &[first.clone(), second.clone()]),
        "{groups:?}"
    );
    assert!(
        groups
            .iter()
            .any(|group| group == std::slice::from_ref(&integration)),
        "{groups:?}"
    );
}
