use eqiora_artifact::ModelEnvelopeV2;
use eqiora_core::entity::kinds;
use eqiora_core::{DimExponents, Entity, Id, OntologyId};
use eqiora_graph::{EdgeKind, GraphStore, InMemoryGraphStore, Op, Transaction};
use eqiora_schema::kernel::{
    ActivationDef, ConnectionDef, ConnectionSemantics, DomainDef, ExprDagBuilder, KernelNode,
    PortDef, RelationDef, SymbolRef,
};
use eqiora_schema::{Model, ModelView};
use eqiora_sem::KernelProgram;
use ulid::Ulid;

// Generated by the unmodified main writer at 2b882ee. SHA-256 commits the
// complete canonical bytes without duplicating the writer's JSON structure in
// this test. The exact byte count additionally catches accidental framing.
const LEGACY_MODEL_DIGEST: &str =
    "ee039e684b2521face498d1d6b2d96255bd0b04a21f6408c46678a9ce31cff2a";
const LEGACY_MODEL_BYTES: usize = 2_741;

fn fixed<E: Entity>(random: u128) -> Id<E> {
    Id::from_ulid(Ulid::from_parts(1_700_000_000_000, random))
}

fn fixture() -> (KernelProgram, OntologyId<Model>) {
    let domain = fixed::<kinds::Domain>(1);
    let first = fixed::<kinds::Port>(2);
    let second = fixed::<kinds::Port>(3);
    let first_relation = fixed::<kinds::Relation>(4);
    let second_relation = fixed::<kinds::Relation>(5);
    let activation = fixed::<kinds::Activation>(6);
    let connection = fixed::<kinds::Connection>(7);
    let model = OntologyId::<Model>::from_ulid(Ulid::from_parts(1_700_000_000_000, 8));
    let across = DimExponents {
        length: 1,
        time: -1,
        ..DimExponents::DIMENSIONLESS
    };
    let through = DimExponents {
        mass: 1,
        length: -1,
        time: -2,
        ..DimExponents::DIMENSIONLESS
    };
    let mut first_expr = ExprDagBuilder::new();
    let first_root = first_expr.symbol(SymbolRef::Across(first)).unwrap();
    let mut second_expr = ExprDagBuilder::new();
    let second_root = second_expr.symbol(SymbolRef::Through(second)).unwrap();
    let nodes = [
        KernelNode::from(DomainDef::scalar_physical(domain, across, through)),
        KernelNode::from(PortDef::scalar_physical(first, domain)),
        KernelNode::from(PortDef::scalar_physical(second, domain)),
        KernelNode::from(RelationDef::new(
            first_relation,
            first_expr.finish([first_root]).unwrap(),
        )),
        KernelNode::from(RelationDef::new(
            second_relation,
            second_expr.finish([second_root]).unwrap(),
        )),
        KernelNode::from(ActivationDef::continuous(activation)),
        KernelNode::from(ConnectionDef::new(
            connection,
            ConnectionSemantics::Conserving,
        )),
    ];
    let view = ModelView::new(model, nodes.iter().map(KernelNode::id), []).unwrap();
    let mut transaction = Transaction::new("fixed v2 scalar physical golden");
    for node in nodes {
        transaction.push(Op::DefineKernelNode { node });
    }
    for (from, to, edge) in [
        (first_relation.erase(), first.erase(), EdgeKind::HasPort),
        (first_relation.erase(), first.erase(), EdgeKind::DependsOn),
        (second_relation.erase(), second.erase(), EdgeKind::HasPort),
        (second_relation.erase(), second.erase(), EdgeKind::DependsOn),
        (
            activation.erase(),
            first_relation.erase(),
            EdgeKind::Activates,
        ),
        (
            activation.erase(),
            second_relation.erase(),
            EdgeKind::Activates,
        ),
        (connection.erase(), first.erase(), EdgeKind::Connects),
        (connection.erase(), second.erase(), EdgeKind::Connects),
    ] {
        transaction.push(Op::Connect { from, to, edge });
    }
    transaction.push(Op::DefineOntologyView { view: view.into() });

    let mut store = InMemoryGraphStore::new();
    store.commit(transaction).unwrap();
    (
        KernelProgram::from_snapshot(&store.snapshot(), model).unwrap(),
        model,
    )
}

#[test]
fn old_main_v2_bytes_digest_and_meaning_remain_fixed() {
    let (program, model) = fixture();
    let envelope = ModelEnvelopeV2::from_program(&program).unwrap();
    let bytes = envelope.canonical_json().unwrap();
    assert_eq!(bytes.len(), LEGACY_MODEL_BYTES);
    assert_eq!(envelope.digest().unwrap().as_str(), LEGACY_MODEL_DIGEST);

    let decoded = ModelEnvelopeV2::from_json(&bytes, Default::default()).unwrap();
    assert_eq!(decoded.canonical_json().unwrap(), bytes);
    assert_eq!(decoded.digest().unwrap().as_str(), LEGACY_MODEL_DIGEST);
    let replay = decoded.to_program().unwrap();
    assert_eq!(replay.model(), model);
    assert_eq!(
        ModelEnvelopeV2::from_program(&replay)
            .unwrap()
            .canonical_json()
            .unwrap(),
        bytes
    );
}
