use eqiora_artifact::{DecoderLimits, ModelEnvelopeV3};
use eqiora_core::entity::kinds;
use eqiora_core::{DimExponents, DynQuantity, Entity, Id, OntologyId};
use eqiora_graph::{EdgeKind, GraphStore, InMemoryGraphStore, Op, Transaction};
use eqiora_schema::kernel::{
    ActivationDef, ExprDagBuilder, FieldDef, KernelNode, RelationDef, SymbolRef,
};
use eqiora_schema::{Model, ModelView};
use eqiora_sem::KernelProgram;
use ulid::Ulid;

// Generated by the v3 writer immediately before v4 was introduced. The
// domain-separated digest and exact byte count freeze the closed v3 writer;
// adding later expression variants must not alter its bytes.
const LEGACY_MODEL_DIGEST: &str =
    "4ef4a803158b6dc63a3de84e64089e4dd06ab64e5e9cdc1dc2c7f15b3cf76a2d";
const LEGACY_MODEL_BYTES: usize = 1_569;

fn fixed<E: Entity>(random: u128) -> Id<E> {
    Id::from_ulid(Ulid::from_parts(1_700_000_000_000, random))
}

fn fixture() -> (KernelProgram, OntologyId<Model>) {
    let field = fixed::<kinds::Field>(1);
    let relation = fixed::<kinds::Relation>(2);
    let activation = fixed::<kinds::Activation>(3);
    let model = OntologyId::<Model>::from_ulid(Ulid::from_parts(1_700_000_000_000, 4));

    let mut expression = ExprDagBuilder::new();
    let value = expression.symbol(SymbolRef::Field(field)).unwrap();
    let zero = expression
        .constant(DynQuantity::new(0.0, DimExponents::DIMENSIONLESS))
        .unwrap();
    let residual = expression.sub(value, zero).unwrap();
    let nodes = [
        KernelNode::from(
            FieldDef::new(field, DimExponents::DIMENSIONLESS)
                .with_initial(DynQuantity::new(1.0, DimExponents::DIMENSIONLESS))
                .unwrap(),
        ),
        KernelNode::from(RelationDef::new(
            relation,
            expression.finish([residual]).unwrap(),
        )),
        KernelNode::from(ActivationDef::continuous(activation)),
    ];

    let mut transaction = Transaction::new("fixed v3 shaped-field golden");
    for node in &nodes {
        transaction.push(Op::DefineKernelNode { node: node.clone() });
    }
    transaction
        .push(Op::Connect {
            from: relation.erase(),
            to: field.erase(),
            edge: EdgeKind::DependsOn,
        })
        .push(Op::Connect {
            from: activation.erase(),
            to: relation.erase(),
            edge: EdgeKind::Activates,
        })
        .push(Op::DefineOntologyView {
            view: ModelView::new(model, nodes.iter().map(KernelNode::id), [])
                .unwrap()
                .into(),
        });

    let mut store = InMemoryGraphStore::new();
    store.commit(transaction).unwrap();
    (
        KernelProgram::from_snapshot(&store.snapshot(), model).unwrap(),
        model,
    )
}

#[test]
fn pre_v4_model_v3_bytes_digest_and_meaning_remain_fixed() {
    let (program, model) = fixture();
    let envelope = ModelEnvelopeV3::from_program(&program).unwrap();
    let bytes = envelope.canonical_json().unwrap();
    assert_eq!(bytes.len(), LEGACY_MODEL_BYTES);
    assert_eq!(envelope.digest().unwrap().as_str(), LEGACY_MODEL_DIGEST);

    let decoded = ModelEnvelopeV3::from_json(&bytes, DecoderLimits::default()).unwrap();
    assert_eq!(decoded.canonical_json().unwrap(), bytes);
    assert_eq!(decoded.digest().unwrap().as_str(), LEGACY_MODEL_DIGEST);
    let replay = decoded.to_program().unwrap();
    assert_eq!(replay.model(), model);
    assert_eq!(
        ModelEnvelopeV3::from_program(&replay)
            .unwrap()
            .canonical_json()
            .unwrap(),
        bytes
    );
}
