from collections.abc import Generator, Iterator, Sequence
from os import PathLike
from typing import (
    Any,
    ClassVar,
    Generic,
    Never,
    Protocol,
    Self,
    TypeVar,
    final,
    overload,
)

import numpy as np
import numpy.typing as npt

from . import fluid as fluid
from . import fsi as fsi
from . import geometry as geometry
from . import meshing as meshing
from . import solid as solid
from . import trajectory as trajectory

_Float64Array = npt.NDArray[np.float64]

__version__: str

class _DLPackProducer(Protocol):
    def __dlpack_device__(self) -> tuple[int, int]: ...
    def __dlpack__(
        self,
        *,
        stream: object | None = ...,
        max_version: tuple[int, int] | None = ...,
        dl_device: tuple[int, int] | None = ...,
        copy: bool | None = ...,
    ) -> object: ...

@final
class Diagnostic:
    @property
    def source(self) -> str: ...
    @property
    def code(self) -> str: ...
    @property
    def severity(self) -> str: ...
    @property
    def message(self) -> str: ...
    @property
    def graph_path(self) -> list[str] | None: ...
    @property
    def source_span(self) -> tuple[str, int, int] | None: ...
    @property
    def suggestion(self) -> str | None: ...

class EqioraError(Exception):
    category: str
    diagnostics: tuple[Diagnostic, ...]

class ValidationError(EqioraError): ...
class CompatibilityError(EqioraError): ...
class CapabilityError(EqioraError): ...
class ExecutionError(EqioraError): ...
class CancellationError(EqioraError): ...
class InternalError(EqioraError): ...

@final
class Dimension:
    def __new__(
        cls,
        *,
        mass: int = 0,
        length: int = 0,
        time: int = 0,
        current: int = 0,
        temperature: int = 0,
        amount: int = 0,
        luminous_intensity: int = 0,
    ) -> Self: ...
    @property
    def exponents(self) -> tuple[int, int, int, int, int, int, int]: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __ne__(self, other: object, /) -> bool: ...

@final
class BoundarySide:
    Lower: ClassVar[BoundarySide]
    Upper: ClassVar[BoundarySide]
    def __eq__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class Domain:
    @staticmethod
    def box(name: str, *bounds: tuple[float, float]) -> Domain: ...
    def boundary(
        self,
        name: str,
        *,
        axis: int,
        side: BoundarySide,
    ) -> Domain: ...
    @property
    def name(self) -> str: ...
    @property
    def bounds(self) -> list[tuple[float, float]] | None: ...
    @property
    def parent(self) -> Domain | None: ...
    @property
    def axis(self) -> int | None: ...
    @property
    def side(self) -> BoundarySide | None: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class Representation:
    @staticmethod
    def continuum(name: str) -> Representation: ...
    @property
    def name(self) -> str: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class Expression:
    def __neg__(self) -> Expression: ...
    def __add__(self, right: _ExpressionLike, /) -> Expression: ...
    def __radd__(self, left: _ExpressionLike, /) -> Expression: ...
    def __sub__(self, right: _ExpressionLike, /) -> Expression: ...
    def __rsub__(self, left: _ExpressionLike, /) -> Expression: ...
    def __mul__(self, right: _ExpressionLike, /) -> Expression: ...
    def __rmul__(self, left: _ExpressionLike, /) -> Expression: ...
    def __truediv__(self, right: _ExpressionLike, /) -> Expression: ...
    def __rtruediv__(self, left: _ExpressionLike, /) -> Expression: ...
    def __bool__(self) -> bool: ...

@final
class Field:
    def __new__(
        cls,
        name: str,
        *,
        domain: Domain | None = None,
        representation: Representation | None = None,
        dimension: Dimension | None = None,
        initial: float = 0.0,
    ) -> Self: ...
    @property
    def name(self) -> str: ...
    @property
    def dimension(self) -> Dimension: ...
    @property
    def initial(self) -> float: ...
    @property
    def domain(self) -> Domain | None: ...
    @property
    def representation(self) -> Representation | None: ...
    def __neg__(self) -> Expression: ...
    def __add__(self, right: _ExpressionLike, /) -> Expression: ...
    def __radd__(self, left: _ExpressionLike, /) -> Expression: ...
    def __sub__(self, right: _ExpressionLike, /) -> Expression: ...
    def __rsub__(self, left: _ExpressionLike, /) -> Expression: ...
    def __mul__(self, right: _ExpressionLike, /) -> Expression: ...
    def __rmul__(self, left: _ExpressionLike, /) -> Expression: ...
    def __truediv__(self, right: _ExpressionLike, /) -> Expression: ...
    def __rtruediv__(self, left: _ExpressionLike, /) -> Expression: ...
    def __bool__(self) -> bool: ...

@final
class Parameter:
    def __new__(
        cls,
        name: str,
        *,
        value: float,
        dimension: Dimension | None = None,
    ) -> Self: ...
    @property
    def name(self) -> str: ...
    @property
    def dimension(self) -> Dimension: ...
    @property
    def value(self) -> float: ...
    def __neg__(self) -> Expression: ...
    def __add__(self, right: _ExpressionLike, /) -> Expression: ...
    def __radd__(self, left: _ExpressionLike, /) -> Expression: ...
    def __sub__(self, right: _ExpressionLike, /) -> Expression: ...
    def __rsub__(self, left: _ExpressionLike, /) -> Expression: ...
    def __mul__(self, right: _ExpressionLike, /) -> Expression: ...
    def __rmul__(self, left: _ExpressionLike, /) -> Expression: ...
    def __truediv__(self, right: _ExpressionLike, /) -> Expression: ...
    def __rtruediv__(self, left: _ExpressionLike, /) -> Expression: ...
    def __bool__(self) -> bool: ...

@final
class PhysicalDomain:
    def __new__(
        cls,
        name: str,
        *,
        across_dimension: Dimension,
        through_dimension: Dimension,
    ) -> Self: ...
    @property
    def name(self) -> str: ...
    @property
    def across_dimension(self) -> Dimension: ...
    @property
    def through_dimension(self) -> Dimension: ...

@final
class ConservingPort:
    def __new__(cls, name: str, *, domain: PhysicalDomain) -> Self: ...
    @property
    def name(self) -> str: ...
    @property
    def domain(self) -> PhysicalDomain: ...

@final
class Connection: ...

_ExpressionLike = Expression | Field | Parameter | float

@final
class Relation:
    @overload
    def __new__(
        cls,
        name: str,
        *,
        domain: Domain | None = None,
        residual: _ExpressionLike,
        residuals: None = None,
    ) -> Self: ...
    @overload
    def __new__(
        cls,
        name: str,
        *,
        domain: Domain | None = None,
        residual: None = None,
        residuals: Sequence[_ExpressionLike],
    ) -> Self: ...
    @property
    def name(self) -> str: ...
    @property
    def residual(self) -> Expression: ...
    @property
    def residuals(self) -> list[Expression]: ...
    @property
    def domain(self) -> Domain | None: ...

@final
class Array:
    def __getitem__(self, index: int, /) -> float: ...
    def numpy(self, *, copy: bool | None = None) -> _Float64Array: ...
    def __array__(
        self, dtype: object | None = None, copy: bool | None = None
    ) -> _Float64Array: ...
    def __dlpack_device__(self) -> tuple[int, int]: ...
    def __dlpack__(
        self,
        *,
        stream: int | None = None,
        max_version: tuple[int, int] | None = None,
        dl_device: tuple[int, int] | None = None,
        copy: bool | None = None,
    ) -> object: ...
    @property
    def device(self) -> str: ...
    @property
    def device_id(self) -> int: ...
    @property
    def dtype(self) -> str: ...
    @property
    def byte_order(self) -> str: ...
    @property
    def shape(self) -> tuple[int]: ...
    @property
    def strides(self) -> tuple[int]: ...
    @property
    def c_contiguous(self) -> bool: ...
    @property
    def aligned(self) -> bool: ...
    @property
    def readonly(self) -> bool: ...
    @property
    def ownership(self) -> str: ...
    @property
    def origin_copy_occurred(self) -> bool: ...
    def __len__(self) -> int: ...

@final
class Revision:
    @property
    def model_id(self) -> str: ...
    @property
    def digest(self) -> str: ...
    @property
    def number(self) -> int: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class StructuralSemanticFingerprint:
    @property
    def generation(self) -> str: ...
    @property
    def digest(self) -> str: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class ValueEdit:
    @property
    def key(self) -> str: ...
    @property
    def base_digest(self) -> str: ...
    @property
    def base_revision(self) -> int: ...
    @property
    def target_id(self) -> str: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class ParameterRef:
    @property
    def model_digest(self) -> str: ...
    @property
    def id(self) -> str: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class FieldRef:
    @property
    def model_digest(self) -> str: ...
    @property
    def id(self) -> str: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class Model:
    @staticmethod
    def define(
        name: str,
        *declarations: _ModelDeclaration,
    ) -> Model: ...
    def to_json(self) -> bytes: ...
    def preview_value_edit(self, target: str, value: float) -> ValueEdit: ...
    def commit(self, edit: ValueEdit) -> Model: ...
    def parameter(self, selection: str) -> ParameterRef: ...
    def field(self, selection: str) -> FieldRef: ...
    def structurally_equivalent(self, other: Model) -> bool: ...
    @property
    def digest(self) -> str: ...
    @property
    def package_compilation_digest(self) -> str | None: ...
    @property
    def structural_fingerprint(self) -> StructuralSemanticFingerprint: ...
    @property
    def revision(self) -> Revision: ...
    @property
    def model_id(self) -> str: ...
    @property
    def field_ids(self) -> list[str]: ...
    @property
    def parameter_ids(self) -> list[str]: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class ScalarEllipticMethod:
    FiniteElement: ClassVar[ScalarEllipticMethod]
    FiniteVolume: ClassVar[ScalarEllipticMethod]
    def __eq__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class ScalarElliptic:
    def __new__(
        cls,
        *,
        method: ScalarEllipticMethod,
        cells_per_axis: int,
        realization_revision: int = 1,
    ) -> Self: ...
    @property
    def method(self) -> ScalarEllipticMethod: ...
    @property
    def cells_per_axis(self) -> int: ...
    @property
    def realization_revision(self) -> int: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class Realization:
    @property
    def digest(self) -> str: ...
    @property
    def model_digest(self) -> str: ...
    @property
    def realization_revision(self) -> int: ...
    @property
    def method(self) -> ScalarEllipticMethod: ...
    @property
    def cells_per_axis(self) -> int: ...
    @property
    def workers(self) -> int: ...
    @property
    def cell_count(self) -> int: ...
    @property
    def field_value_count(self) -> int: ...
    @property
    def spatial_dimension(self) -> int: ...
    @property
    def field_logical_shape(self) -> tuple[int, ...]: ...
    @property
    def field_bounds(self) -> tuple[tuple[float, float], ...]: ...
    def to_json(self) -> bytes: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class ScalarFieldLocation:
    Vertex: ClassVar[ScalarFieldLocation]
    CellCenter: ClassVar[ScalarFieldLocation]
    def __eq__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class ScalarFieldSummary:
    @property
    def location(self) -> ScalarFieldLocation: ...
    @property
    def spatial_dimension(self) -> int: ...
    @property
    def logical_shape(self) -> tuple[int, ...]: ...
    @property
    def value_count(self) -> int: ...
    @property
    def minimum(self) -> float: ...
    @property
    def maximum(self) -> float: ...

@final
class ScalarEllipticBalance:
    @property
    def boundary_total(self) -> float: ...
    @property
    def integrated_source(self) -> float: ...
    @property
    def relative_imbalance(self) -> float: ...

@final
class ConvergenceReason:
    InitialResidualSatisfied: ClassVar[ConvergenceReason]
    ResidualToleranceSatisfied: ClassVar[ConvergenceReason]
    def __eq__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class LinearSolveSummary:
    @property
    def backend(self) -> str: ...
    @property
    def adapter(self) -> str: ...
    @property
    def verification_adapter(self) -> str: ...
    @property
    def orientation(self) -> str: ...
    @property
    def algorithm(self) -> str: ...
    @property
    def preconditioner(self) -> str: ...
    @property
    def reduction(self) -> str: ...
    @property
    def relative_tolerance(self) -> float: ...
    @property
    def absolute_tolerance(self) -> float: ...
    @property
    def maximum_iterations(self) -> int: ...
    @property
    def reason(self) -> ConvergenceReason: ...
    @property
    def completed_iterations(self) -> int: ...
    @property
    def initial_residual_norm(self) -> float: ...
    @property
    def reported_residual_norm(self) -> float: ...
    @property
    def true_residual_norm(self) -> float: ...
    @property
    def residual_target(self) -> float: ...

@final
class DifferentiationMode:
    Primal: ClassVar[DifferentiationMode]
    Jvp: ClassVar[DifferentiationMode]
    Vjp: ClassVar[DifferentiationMode]
    def __eq__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class DerivativeImplementation:
    AnalyticAssembled: ClassVar[DerivativeImplementation]
    def __eq__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class LinearizationState:
    Established: ClassVar[LinearizationState]
    Reused: ClassVar[LinearizationState]
    def __eq__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class DifferentiationEvidence:
    @property
    def model_digest(self) -> str: ...
    @property
    def realization_digest(self) -> str: ...
    @property
    def input_ids(self) -> list[str]: ...
    @property
    def output_id(self) -> str: ...
    @property
    def mode(self) -> DifferentiationMode: ...
    @property
    def implementation(self) -> DerivativeImplementation: ...
    @property
    def linearization_state(self) -> LinearizationState: ...
    @property
    def state_system_fingerprint(self) -> str: ...
    @property
    def primal_residual_norm(self) -> float: ...
    @property
    def residual_tolerance(self) -> float: ...
    @property
    def primal_solve(self) -> LinearSolveSummary: ...
    @property
    def derivative_solve(self) -> LinearSolveSummary | None: ...

@final
class DifferentiablePrimal:
    @property
    def output(self) -> Array: ...
    @property
    def evidence(self) -> DifferentiationEvidence: ...

@final
class DifferentiableJvp:
    @property
    def output(self) -> Array: ...
    @property
    def tangent(self) -> Array: ...
    @property
    def evidence(self) -> DifferentiationEvidence: ...

@final
class DifferentiableVjp:
    @property
    def output(self) -> Array: ...
    @property
    def input_cotangent(self) -> Array: ...
    @property
    def evidence(self) -> DifferentiationEvidence: ...

@final
class DifferentiableEvaluation:
    @property
    def point(self) -> Array: ...
    def primal(self) -> DifferentiablePrimal: ...
    def jvp(
        self, tangent: Array | _Float64Array | _DLPackProducer
    ) -> DifferentiableJvp: ...
    def vjp(
        self, cotangent: Array | _Float64Array | _DLPackProducer
    ) -> DifferentiableVjp: ...

@final
class DifferentiableProgram:
    @property
    def model_digest(self) -> str: ...
    @property
    def realization_digest(self) -> str: ...
    @property
    def input_ids(self) -> list[str]: ...
    @property
    def output_id(self) -> str: ...
    @property
    def input_shape(self) -> tuple[int]: ...
    @property
    def output_shape(self) -> tuple[int]: ...
    @property
    def dtype(self) -> str: ...
    @property
    def device(self) -> str: ...
    @property
    def derivative_contract(self) -> str: ...
    def evaluate(
        self, parameters: Array | _Float64Array | _DLPackProducer
    ) -> DifferentiableEvaluation: ...
    def primal(self) -> DifferentiablePrimal: ...
    def jvp(
        self, tangent: Array | _Float64Array | _DLPackProducer
    ) -> DifferentiableJvp: ...
    def vjp(
        self, cotangent: Array | _Float64Array | _DLPackProducer
    ) -> DifferentiableVjp: ...

@final
class RunManifest:
    @staticmethod
    def from_json(data: bytes, *, realization: Realization) -> RunManifest: ...
    @property
    def digest(self) -> str: ...
    @property
    def model_digest(self) -> str: ...
    @property
    def realization_digest(self) -> str: ...
    @property
    def semantic_revision(self) -> int: ...
    @property
    def output_digests(self) -> list[str]: ...
    @property
    def adapter(self) -> str: ...
    @property
    def adapter_version(self) -> str: ...
    @property
    def solver_backend(self) -> str: ...
    @property
    def solver_backend_version(self) -> str: ...
    @property
    def workers(self) -> int: ...
    @property
    def reduction(self) -> str: ...
    def to_json(self) -> bytes: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class ScalarEllipticResult:
    @property
    def realization(self) -> Realization: ...
    @property
    def run_manifest(self) -> RunManifest: ...
    @property
    def elapsed_seconds(self) -> float: ...
    @property
    def field(self) -> ScalarFieldSummary: ...
    @property
    def values(self) -> Array: ...
    @property
    def balance(self) -> ScalarEllipticBalance: ...
    @property
    def solve(self) -> LinearSolveSummary: ...
    @property
    def output_fingerprint(self) -> str: ...

@final
class Series:
    @property
    def id(self) -> str: ...
    @property
    def name(self) -> str | None: ...
    @property
    def dimension(self) -> tuple[int, int, int, int, int, int, int]: ...
    @property
    def time(self) -> Array: ...
    @property
    def values(self) -> Array: ...
    def __len__(self) -> int: ...
    def __iter__(self) -> Iterator[tuple[float, float]]: ...

@final
class Result:
    @property
    def model_id(self) -> str: ...
    @property
    def model_digest(self) -> str: ...
    @property
    def model_revision(self) -> int: ...
    @property
    def plan_key(self) -> str: ...
    @property
    def adapter(self) -> str: ...
    @property
    def adapter_version(self) -> str: ...
    @property
    def elapsed_seconds(self) -> float: ...
    @property
    def fields(self) -> list[Series]: ...
    @property
    def snapshots(self) -> tuple[trajectory.FieldSnapshot, ...]: ...
    def field(self, field: FieldRef, /) -> trajectory.FieldSnapshot: ...
    def mesh(self, field: FieldRef, /) -> meshing.Mesh: ...
    @property
    def trajectory(self) -> trajectory.Trajectory: ...
    def run_manifest(self) -> RunManifest: ...
    def __len__(self) -> int: ...
    def __getitem__(self, key: str, /) -> Series: ...

@final
class RunStatus:
    Created: ClassVar[RunStatus]
    Validating: ClassVar[RunStatus]
    Queued: ClassVar[RunStatus]
    Running: ClassVar[RunStatus]
    Cancelling: ClassVar[RunStatus]
    Cancelled: ClassVar[RunStatus]
    Completed: ClassVar[RunStatus]
    Failed: ClassVar[RunStatus]
    def __eq__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class RunProgress:
    @property
    def model_time(self) -> float: ...
    @property
    def end_time(self) -> float: ...
    @property
    def accepted_steps(self) -> int: ...
    @property
    def maximum_steps(self) -> int: ...

@final
class RunCancellation:
    @property
    def progress(self) -> RunProgress: ...
    @property
    def elapsed_seconds(self) -> float: ...
    @property
    def plan_key(self) -> str: ...

@final
class ScalarEllipticRunProgress:
    PlanReplayed: ClassVar[ScalarEllipticRunProgress]
    SystemFinalized: ClassVar[ScalarEllipticRunProgress]
    SolutionAccepted: ClassVar[ScalarEllipticRunProgress]
    def __eq__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class ScalarEllipticRunCancellation:
    @property
    def progress(self) -> ScalarEllipticRunProgress: ...
    @property
    def elapsed_seconds(self) -> float: ...
    @property
    def plan_key(self) -> str: ...

_RunResultT = TypeVar(
    "_RunResultT",
    Result,
    ScalarEllipticResult,
)

class Run(Generic[_RunResultT]):
    def __init__(self, native: Never) -> None: ...
    @property
    def status(self) -> RunStatus: ...
    @property
    def history(self) -> tuple[RunStatus, ...]: ...
    @property
    def progress(self) -> RunProgress | ScalarEllipticRunProgress | None: ...
    @property
    def cancellation(
        self,
    ) -> RunCancellation | ScalarEllipticRunCancellation | None: ...
    @property
    def done(self) -> bool: ...
    @property
    def model_id(self) -> str: ...
    @property
    def model_digest(self) -> str: ...
    @property
    def model_revision(self) -> int: ...
    @property
    def plan_key(self) -> str: ...
    @property
    def adapter(self) -> str: ...
    def cancel(self) -> bool: ...
    def result(self) -> _RunResultT: ...
    def __await__(self) -> Generator[Any, None, _RunResultT]: ...

_ModelDeclaration = (
    Domain
    | Representation
    | Field
    | Parameter
    | PhysicalDomain
    | ConservingPort
    | Relation
    | Connection
)

def across(port: ConservingPort) -> Expression: ...
def compile(
    source: str,
    *,
    filename: str = "<memory>",
) -> Model: ...
def compile_package(
    store_root: str | PathLike[str],
    resolution: bytes,
    *,
    entry_model: str,
) -> Model: ...
def connect(*ports: ConservingPort) -> Connection: ...
def derivative(field: Field) -> Expression: ...
def div(value: _ExpressionLike) -> Expression: ...
def grad(value: _ExpressionLike) -> Expression: ...
def preview_realization(model: Model, request: ScalarElliptic) -> Realization: ...
def replay(data: bytes) -> Model: ...
@overload
def run(
    model: Model,
    *,
    end_time: float,
    max_step: float,
    realization: None = None,
) -> Result: ...
@overload
def run(model: Model, *, realization: Realization) -> ScalarEllipticResult: ...
@overload
def run(
    model: Model,
    *,
    plan: fluid.SteadyStokesPlan,
) -> Result: ...
@overload
def run(
    model: Model,
    *,
    plan: solid.LinearElasticityPlan,
) -> Result: ...
@overload
def run(
    model: Model,
    *,
    plan: fsi.FixedMeshMonolithicPlan,
) -> Result: ...
@overload
def submit(
    model: Model,
    *,
    end_time: float,
    max_step: float,
    realization: None = None,
) -> Run[Result]: ...
@overload
def submit(model: Model, *, realization: Realization) -> Run[ScalarEllipticResult]: ...
@overload
def submit(
    model: Model,
    *,
    plan: fluid.SteadyStokesPlan,
) -> Run[Result]: ...
@overload
def submit(
    model: Model,
    *,
    plan: solid.LinearElasticityPlan,
) -> Run[Result]: ...
@overload
def submit(
    model: Model,
    *,
    plan: fsi.FixedMeshMonolithicPlan,
) -> Run[Result]: ...
def through(port: ConservingPort) -> Expression: ...
def trace(value: _ExpressionLike) -> Expression: ...

from . import diff as diff

__all__ = [
    "__version__",
    "Array",
    "BoundarySide",
    "CancellationError",
    "CapabilityError",
    "CompatibilityError",
    "Connection",
    "ConservingPort",
    "ConvergenceReason",
    "DerivativeImplementation",
    "Diagnostic",
    "DifferentiableEvaluation",
    "DifferentiableJvp",
    "DifferentiablePrimal",
    "DifferentiableProgram",
    "DifferentiableVjp",
    "DifferentiationEvidence",
    "DifferentiationMode",
    "Dimension",
    "Domain",
    "EqioraError",
    "ExecutionError",
    "Expression",
    "Field",
    "FieldRef",
    "InternalError",
    "LinearSolveSummary",
    "LinearizationState",
    "Model",
    "Parameter",
    "ParameterRef",
    "PhysicalDomain",
    "Realization",
    "Representation",
    "Relation",
    "Result",
    "Revision",
    "Run",
    "RunManifest",
    "RunCancellation",
    "RunProgress",
    "RunStatus",
    "ScalarElliptic",
    "ScalarEllipticBalance",
    "ScalarEllipticMethod",
    "ScalarEllipticResult",
    "ScalarEllipticRunCancellation",
    "ScalarEllipticRunProgress",
    "ScalarFieldLocation",
    "ScalarFieldSummary",
    "Series",
    "StructuralSemanticFingerprint",
    "ValidationError",
    "ValueEdit",
    "across",
    "compile",
    "compile_package",
    "connect",
    "derivative",
    "div",
    "grad",
    "preview_realization",
    "replay",
    "run",
    "submit",
    "through",
    "trace",
    "diff",
    "fluid",
    "fsi",
    "geometry",
    "meshing",
    "solid",
    "trajectory",
]
