"""Closed finite-element spatial policies.

Authority: ``crates/eqiora-python/src/common_plan/policy.rs::PyQ1``.
"""
from typing import Self, final
from . import DomainRef

@final
class ScopedSpatialPolicy:
    """One exact Model-Domain-bound spatial policy.

    Authority: ``crates/eqiora-python/src/common_plan/policy.rs::PyScopedSpatialBinding``.
    """
    @property
    def domain(self) -> DomainRef: ...
    @property
    def method(self) -> str: ...
    @property
    def spaces(self) -> tuple[str, str | None]: ...
    @property
    def quadrature(self) -> str: ...

@final
class Q1:
    """Continuous tensor-product Q1 Galerkin spatial policy.

    Authority: ``crates/eqiora-python/src/common_plan/policy.rs::PyQ1``.
    """
    def __new__(cls) -> Self: ...
    @property
    def method(self) -> str: ...
    @property
    def space(self) -> str: ...
    @property
    def quadrature(self) -> str: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...

@final
class MiniP1:
    """Mixed MINI velocity and continuous P1 pressure spatial policy.

    Authority: ``crates/eqiora-python/src/common_plan/policy.rs::PyMiniP1``.
    """
    def __new__(cls) -> Self: ...
    @property
    def method(self) -> str: ...
    @property
    def velocity_space(self) -> str: ...
    @property
    def pressure_space(self) -> str: ...
    @property
    def quadrature(self) -> str: ...
    def at(self, domain: DomainRef) -> ScopedSpatialPolicy: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...

@final
class P1:
    """Continuous simplex P1 Galerkin spatial policy.

    Authority: ``crates/eqiora-python/src/common_plan/policy.rs::PyP1``.
    """
    def __new__(cls) -> Self: ...
    @property
    def method(self) -> str: ...
    @property
    def space(self) -> str: ...
    @property
    def quadrature(self) -> str: ...
    def at(self, domain: DomainRef) -> ScopedSpatialPolicy: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...

__all__ = ["MiniP1", "P1", "Q1", "ScopedSpatialPolicy"]
