from typing import final

import numpy as np
import numpy.typing as npt

from . import Array, LinearSolveSummary, Model
from .meshing import Mesh

@final
class SteadyStokes:
    def __new__(
        cls,
        *,
        length_scale_m: float,
        velocity_scale_m_per_s: float,
        pressure_scale_pa: float,
        relative_tolerance: float,
        absolute_tolerance: float,
        maximum_iterations: int,
    ) -> SteadyStokes: ...
    @property
    def length_scale_m(self) -> float: ...
    @property
    def velocity_scale_m_per_s(self) -> float: ...
    @property
    def pressure_scale_pa(self) -> float: ...
    @property
    def relative_tolerance(self) -> float: ...
    @property
    def absolute_tolerance(self) -> float: ...
    @property
    def maximum_iterations(self) -> int: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class SteadyStokesPlan:
    @property
    def model_digest(self) -> str: ...
    @property
    def semantic_revision(self) -> int: ...
    @property
    def geometry_digest(self) -> str: ...
    @property
    def correspondence_digest(self) -> str: ...
    @property
    def mesh_digest(self) -> str: ...
    @property
    def realization_digest(self) -> str: ...
    @property
    def realization_revision(self) -> int: ...
    @property
    def spatial_dimension(self) -> int: ...
    @property
    def velocity_space(self) -> str: ...
    @property
    def pressure_space(self) -> str: ...
    @property
    def length_scale_m(self) -> float: ...
    @property
    def velocity_scale_m_per_s(self) -> float: ...
    @property
    def pressure_scale_pa(self) -> float: ...
    @property
    def solver_algorithm(self) -> str: ...
    @property
    def preconditioner(self) -> str: ...
    @property
    def reduction(self) -> str: ...
    @property
    def relative_tolerance(self) -> float: ...
    @property
    def absolute_tolerance(self) -> float: ...
    @property
    def maximum_iterations(self) -> int: ...
    @property
    def solver_backend(self) -> str: ...
    @property
    def execution_adapter(self) -> str: ...
    @property
    def workers(self) -> int: ...
    @property
    def canonical_bytes(self) -> bytes: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class CircularHoleSteadyStokesResult:
    @property
    def model_digest(self) -> str: ...
    @property
    def semantic_revision(self) -> int: ...
    @property
    def chordal_realization_digest(self) -> str: ...
    @property
    def chordal_realization_json(self) -> bytes: ...
    @property
    def exact_source_digest(self) -> str: ...
    @property
    def realized_geometry_digest(self) -> str: ...
    @property
    def correspondence_digest(self) -> str: ...
    @property
    def realization_digest(self) -> str: ...
    @property
    def realization_revision(self) -> int: ...
    @property
    def run_digest(self) -> str: ...
    @property
    def run_manifest_json(self) -> bytes: ...
    @property
    def snapshot_digest(self) -> str: ...
    @property
    def mesh_digest(self) -> str: ...
    @property
    def pressure_field_id(self) -> str: ...
    @property
    def support_domain_id(self) -> str: ...
    @property
    def pressure_dimension(self) -> tuple[int, int, int, int, int, int, int]: ...
    @property
    def bounds(self) -> tuple[tuple[float, float], tuple[float, float]]: ...
    @property
    def coordinates(self) -> npt.NDArray[np.float64]: ...
    @property
    def triangles(self) -> npt.NDArray[np.uint32]: ...
    @property
    def pressure(self) -> Array: ...
    @property
    def pressure_minimum(self) -> float: ...
    @property
    def pressure_maximum(self) -> float: ...
    @property
    def requested_max_boundary_error(self) -> float: ...
    @property
    def boundary_evaluation_allowance(self) -> float: ...
    @property
    def boundary_error_bound(self) -> float: ...
    @property
    def circle_segments(self) -> int: ...
    @property
    def cylinder_force_on_fluid(self) -> tuple[float, float]: ...
    @property
    def inlet_flux(self) -> float: ...
    @property
    def outlet_flux(self) -> float: ...
    @property
    def net_flux(self) -> float: ...
    @property
    def constrained_reaction(self) -> tuple[float, float]: ...
    @property
    def integrated_body_force(self) -> tuple[float, float]: ...
    @property
    def integrated_boundary_traction(self) -> tuple[float, float]: ...
    @property
    def momentum_closure(self) -> tuple[float, float]: ...
    @property
    def solve(self) -> LinearSolveSummary: ...
    @property
    def continuity_residual_norm(self) -> float: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...

def resolve(
    model: Model,
    intent: SteadyStokes,
    /,
    *,
    mesh: Mesh,
) -> SteadyStokesPlan: ...

__all__ = [
    "CircularHoleSteadyStokesResult",
    "SteadyStokes",
    "SteadyStokesPlan",
    "resolve",
]
