"""Observation-only evidence for common FSI Results.

Authority: ``bindings/python/python/eqiora/fsi.py``.
"""

from typing import final
import numpy as np
import numpy.typing as npt
from . import LinearSolveSummary, Result, State

@final
class FsiStateEvidence:
    """Numerical observations for one exact accepted common FSI State.

    Authority: ``crates/eqiora-python/src/fsi_evidence.rs::PyFsiStateEvidence``.
    """
    @property
    def state_digest(self) -> str: ...
    @property
    def interface_vertices(self) -> npt.NDArray[np.uint32]: ...
    @property
    def fluid_action(self) -> npt.NDArray[np.float64]: ...
    @property
    def solid_action(self) -> npt.NDArray[np.float64]: ...
    @property
    def action_imbalance(self) -> npt.NDArray[np.float64]: ...
    @property
    def previous_kinetic_energy_j_per_m(self) -> float: ...
    @property
    def next_kinetic_energy_j_per_m(self) -> float: ...
    @property
    def previous_elastic_energy_j_per_m(self) -> float: ...
    @property
    def next_elastic_energy_j_per_m(self) -> float: ...
    @property
    def kinetic_increment_j_per_m(self) -> float: ...
    @property
    def elastic_increment_j_per_m(self) -> float: ...
    @property
    def viscous_dissipation_j_per_m(self) -> float: ...
    @property
    def energy_defect_j_per_m(self) -> float: ...
    @property
    def numerical_residual_norm(self) -> float: ...
    @property
    def continuity_residual_norm(self) -> float: ...
    @property
    def kinematic_residual_norm(self) -> float: ...
    @property
    def interface_velocity_jump_norm(self) -> float: ...
    @property
    def interface_action_imbalance_n_per_m(self) -> float: ...
    @property
    def solve(self) -> LinearSolveSummary: ...
    @property
    def assembly_packets(self) -> int: ...
    @property
    def assembly_targets(self) -> int: ...

@final
class FsiEvidence:
    """Observation-only partition and per-State evidence for a common FSI Result.

    Authority: ``crates/eqiora-python/src/fsi_evidence.rs::PyFsiEvidence``.
    """
    @property
    def request_identity(self) -> str: ...
    @property
    def fluid_cells(self) -> npt.NDArray[np.uint32]: ...
    @property
    def solid_cells(self) -> npt.NDArray[np.uint32]: ...
    @property
    def interface_facets(self) -> npt.NDArray[np.uint32]: ...
    @property
    def states(self) -> tuple[FsiStateEvidence, ...]: ...
    def state(self, state: State) -> FsiStateEvidence: ...

def evidence(result: Result) -> FsiEvidence:
    """Select observation-only FSI evidence from an accepted common Result.

    Authority: ``crates/eqiora-python/src/fsi_evidence.rs::evidence``.
    """
    ...

__all__ = ["FsiEvidence", "FsiStateEvidence", "evidence"]
