from typing import final

import numpy as np
import numpy.typing as npt

from . import LinearSolveSummary, Model
from .trajectory import Trajectory

@final
class FixedReferenceFsiStep:
    @property
    def ordinal(self) -> int: ...
    @property
    def time_s(self) -> float: ...
    @property
    def velocity(self) -> npt.NDArray[np.float64]: ...
    @property
    def bubble_velocity(self) -> npt.NDArray[np.float64]: ...
    @property
    def pressure_vertices(self) -> npt.NDArray[np.uint32]: ...
    @property
    def pressure(self) -> npt.NDArray[np.float64]: ...
    @property
    def displacement(self) -> npt.NDArray[np.float64]: ...
    @property
    def interface_vertices(self) -> npt.NDArray[np.uint32]: ...
    @property
    def fluid_action(self) -> npt.NDArray[np.float64]: ...
    @property
    def solid_action(self) -> npt.NDArray[np.float64]: ...
    @property
    def action_imbalance(self) -> npt.NDArray[np.float64]: ...
    @property
    def previous_kinetic_energy_j_per_m(self) -> float: ...
    @property
    def next_kinetic_energy_j_per_m(self) -> float: ...
    @property
    def previous_elastic_energy_j_per_m(self) -> float: ...
    @property
    def next_elastic_energy_j_per_m(self) -> float: ...
    @property
    def kinetic_increment_j_per_m(self) -> float: ...
    @property
    def elastic_increment_j_per_m(self) -> float: ...
    @property
    def viscous_dissipation_j_per_m(self) -> float: ...
    @property
    def energy_defect_j_per_m(self) -> float: ...
    @property
    def numerical_residual_norm(self) -> float: ...
    @property
    def continuity_residual_norm(self) -> float: ...
    @property
    def kinematic_residual_norm(self) -> float: ...
    @property
    def interface_velocity_jump_norm(self) -> float: ...
    @property
    def interface_action_imbalance_n_per_m(self) -> float: ...
    @property
    def solve(self) -> LinearSolveSummary: ...
    @property
    def assembly_packets(self) -> int: ...
    @property
    def assembly_targets(self) -> int: ...
    def __repr__(self) -> str: ...

@final
class FixedReferenceFsiResult:
    @property
    def semantic_revision(self) -> int: ...
    @property
    def realization_revision(self) -> int: ...
    @property
    def run_manifest_json(self) -> bytes: ...
    @property
    def trajectory(self) -> Trajectory: ...
    @property
    def fluid_cells(self) -> npt.NDArray[np.uint32]: ...
    @property
    def solid_cells(self) -> npt.NDArray[np.uint32]: ...
    @property
    def interface_facets(self) -> npt.NDArray[np.uint32]: ...
    @property
    def steps(self) -> tuple[FixedReferenceFsiStep, FixedReferenceFsiStep]: ...
    def step(self, ordinal: int, /) -> FixedReferenceFsiStep: ...
    @property
    def case_ids(self) -> tuple[str, str]: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...

def solve_fixed_reference_fsi(
    model: Model,
    /,
) -> FixedReferenceFsiResult: ...

__all__ = [
    "FixedReferenceFsiResult",
    "FixedReferenceFsiStep",
    "solve_fixed_reference_fsi",
]
