"""Closed finite-volume spatial policies.

Authority: ``crates/eqiora-python/src/common_plan/policy.rs::PyCellCenteredTpfa``.
"""
from typing import Self, final

@final
class CellCenteredTpfa:
    """Cell-centred orthogonal two-point-flux spatial policy.

    Authority: ``crates/eqiora-python/src/common_plan/policy.rs::PyCellCenteredTpfa``.
    """
    def __new__(cls) -> Self: ...
    @property
    def method(self) -> str: ...
    @property
    def space(self) -> str: ...
    @property
    def quadrature(self) -> str: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...

@final
class CellCentered:
    """Collocated cell-centred incompressible-flow spatial policy.

    Authority: ``crates/eqiora-python/src/common_plan/policy.rs::PyCellCentered``.
    """
    def __new__(cls) -> Self: ...
    @property
    def method(self) -> str: ...
    @property
    def velocity_space(self) -> str: ...
    @property
    def pressure_space(self) -> str: ...
    @property
    def quadrature(self) -> str: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...

__all__ = ["CellCentered", "CellCenteredTpfa"]
