"""Bounded exact geometry values owned by the native implementation.

Authority: ``bindings/python/python/eqiora/geometry.py``.
"""

from typing import final

@final
class CadAuthoredFaceHandle:
    """Authored-face provenance bound to one exact graph digest.

    Authority: ``crates/eqiora-python/src/cad_authored.rs::PyCadAuthoredFaceHandle``.
    """

    @staticmethod
    def decode_canonical(data: bytes) -> CadAuthoredFaceHandle: ...
    @property
    def canonical_bytes(self) -> bytes: ...
    @property
    def graph_digest(self) -> str: ...
    @property
    def provenance_key(self) -> str: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class CadAuthoredBuild:
    """Read-only receipt from the bounded native analytic CAD profile.

    Authority: ``crates/eqiora-python/src/cad_authored.rs::PyCadAuthoredBuild``.
    """

    @property
    def graph_digest(self) -> str: ...
    @property
    def provider_profile(self) -> str: ...
    @property
    def requested_modeling_tolerance(self) -> float: ...
    @property
    def requested_boolean_tolerance(self) -> float | None: ...
    @property
    def effective_boolean_tolerance(self) -> float | None: ...
    @property
    def maximum_position_discrepancy(self) -> float: ...
    @property
    def maximum_area_discrepancy(self) -> float: ...
    @property
    def maximum_volume_discrepancy(self) -> float: ...
    @property
    def repair(self) -> str: ...
    @property
    def retained_unchanged(self) -> tuple[CadAuthoredFaceHandle, ...]: ...
    @property
    def retained_modified(self) -> tuple[CadAuthoredFaceHandle, ...]: ...
    @property
    def created(self) -> tuple[CadAuthoredFaceHandle, ...]: ...
    @property
    def deleted(self) -> tuple[CadAuthoredFaceHandle, ...]: ...
    @property
    def split(self) -> tuple[CadAuthoredFaceHandle, ...]: ...
    @property
    def merged(self) -> tuple[CadAuthoredFaceHandle, ...]: ...
    def __eq__(self, other: object, /) -> bool: ...

@final
class CadAuthoredGraph:
    """Immutable native-owned authored-CAD operation graph.

    Authority: ``crates/eqiora-python/src/cad_authored.rs::PyCadAuthoredGraph``.
    """

    @staticmethod
    def rectangle_extrusion(
        *,
        x_bounds: tuple[float, float],
        y_bounds: tuple[float, float],
        plane_z: float,
        depth: float,
        modeling_tolerance: float,
    ) -> CadAuthoredGraph: ...
    @staticmethod
    def decode_canonical(data: bytes) -> CadAuthoredGraph: ...
    def circular_through_cut(
        self,
        *,
        center: tuple[float, float],
        radius: float,
        boolean_tolerance: float,
    ) -> CadAuthoredGraph: ...
    def through_cut(
        self,
        sketch: CadAuthoredSketch,
        /,
        *,
        boolean_tolerance: float,
    ) -> CadAuthoredGraph: ...
    def planar_circular_section(
        self,
        *,
        classification_tolerance: float,
        region: str,
        x_lower: str,
        x_upper: str,
        y_lower: str,
        y_upper: str,
        hole: str,
    ) -> Geometry: ...
    @property
    def canonical_bytes(self) -> bytes: ...
    @property
    def graph_digest(self) -> str: ...
    @property
    def x_bounds(self) -> tuple[float, float]: ...
    @property
    def y_bounds(self) -> tuple[float, float]: ...
    @property
    def plane_z(self) -> float: ...
    @property
    def extrusion_depth(self) -> float: ...
    @property
    def requested_modeling_tolerance(self) -> float: ...
    @property
    def requested_boolean_tolerance(self) -> float | None: ...
    @property
    def cut_center(self) -> tuple[float, float] | None: ...
    @property
    def cut_radius(self) -> float | None: ...
    @property
    def bounds(
        self,
    ) -> tuple[tuple[float, float], tuple[float, float], tuple[float, float]]: ...
    @property
    def vertex_count(self) -> int | None: ...
    @property
    def edge_count(self) -> int | None: ...
    @property
    def face_count(self) -> int: ...
    @property
    def closed_shell_count(self) -> int: ...
    @property
    def body_count(self) -> int: ...
    @property
    def genus(self) -> int: ...
    @property
    def volume(self) -> float: ...
    @property
    def surface_area(self) -> float: ...
    @property
    def repair(self) -> str: ...
    @property
    def selection_names(self) -> tuple[str, ...]: ...
    def face_handle(self, name: str) -> CadAuthoredFaceHandle: ...
    def resolve_face(self, handle: CadAuthoredFaceHandle) -> str: ...
    def face_area(self, handle: CadAuthoredFaceHandle) -> float: ...
    def face_boundary_loop_count(self, handle: CadAuthoredFaceHandle) -> int: ...
    def rectangular_face_vertices(
        self, handle: CadAuthoredFaceHandle
    ) -> tuple[tuple[float, float, float], ...] | None: ...
    def rectangular_face_centroid(
        self, handle: CadAuthoredFaceHandle
    ) -> tuple[float, float, float] | None: ...
    def planar_face_outward_normal(
        self, handle: CadAuthoredFaceHandle
    ) -> tuple[float, float, float] | None: ...
    def build(self) -> CadAuthoredBuild: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...

@final
class CadAuthoredSketch:
    """Opaque native-owned input for closed authored-CAD operations.

    Authority: ``crates/eqiora-python/src/cad_authored.rs::PyCadAuthoredSketch``.
    """

    @staticmethod
    def rectangle_xy(
        *,
        x_bounds: tuple[float, float],
        y_bounds: tuple[float, float],
        plane_z: float,
        modeling_tolerance: float,
    ) -> CadAuthoredSketch: ...
    @staticmethod
    def circle_on_face(
        face: CadAuthoredFaceHandle,
        /,
        *,
        center: tuple[float, float],
        radius: float,
    ) -> CadAuthoredSketch: ...
    def extrude_positive_z(
        self,
        *,
        depth: float,
    ) -> CadAuthoredGraph: ...
    def __eq__(self, other: object, /) -> bool: ...

@final
class Geometry:
    """Immutable exact geometry produced by an accepted authored graph.

    Authority: ``crates/eqiora-python/src/geometry.rs::PyGeometry``.
    """

    @property
    def dimension(self) -> int: ...
    @property
    def bounds(self) -> tuple[tuple[float, float], tuple[float, float]]: ...
    @property
    def classification_tolerance(self) -> float: ...
    @property
    def canonical_bytes(self) -> bytes: ...
    @property
    def digest(self) -> str: ...
    @property
    def selection_names(self) -> tuple[str, ...]: ...
    def selection_dimension(self, name: str) -> int: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...

__all__ = [
    "CadAuthoredBuild",
    "CadAuthoredFaceHandle",
    "CadAuthoredGraph",
    "CadAuthoredSketch",
    "Geometry",
]
