from typing import Self, final

@final
class RectangleWithCircularHole:
    def __new__(
        cls,
        *,
        bounds: tuple[tuple[float, float], tuple[float, float]],
        circle_center: tuple[float, float],
        circle_radius: float,
        tolerance: float,
        region: str,
        x_lower: str,
        x_upper: str,
        y_lower: str,
        y_upper: str,
        hole: str,
    ) -> Self: ...
    @property
    def bounds(self) -> tuple[tuple[float, float], tuple[float, float]]: ...
    @property
    def circle_center(self) -> tuple[float, float]: ...
    @property
    def circle_radius(self) -> float: ...
    @property
    def tolerance(self) -> float: ...
    @property
    def canonical_json(self) -> bytes: ...
    @property
    def digest(self) -> str: ...
    @property
    def selection_names(self) -> tuple[str, ...]: ...
    def selection_dimension(self, name: str) -> int: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...

__all__ = ["RectangleWithCircularHole"]
