from typing import final

from .geometry import RectangleWithCircularHole

@final
class CircularHoleChordalMesh:
    @property
    def source_digest(self) -> str: ...
    @property
    def mesh_digest(self) -> str: ...
    @property
    def mesh_canonical_json(self) -> bytes: ...
    @property
    def dimension(self) -> int: ...
    @property
    def vertex_count(self) -> int: ...
    @property
    def cell_count(self) -> int: ...
    @property
    def requested_max_boundary_error(self) -> float: ...
    @property
    def boundary_evaluation_allowance(self) -> float: ...
    @property
    def boundary_error_bound(self) -> float: ...
    @property
    def circle_segments(self) -> int: ...
    @property
    def circle_area_deficit(self) -> float: ...
    @property
    def circle_perimeter_deficit(self) -> float: ...
    @property
    def required_minimum_mean_ratio(self) -> float: ...
    @property
    def minimum_mean_ratio(self) -> float: ...
    @property
    def selection_names(self) -> tuple[str, ...]: ...
    def selection_entity_count(self, name: str) -> int: ...

def circular_hole_chordal(
    geometry: RectangleWithCircularHole,
    *,
    max_boundary_error: float = ...,
    required_minimum_mean_ratio: float = ...,
    max_segments: int = ...,
) -> CircularHoleChordalMesh: ...

__all__ = ["CircularHoleChordalMesh", "circular_hole_chordal"]
