from typing import final

import numpy as np
import numpy.typing as npt

from . import LinearSolveSummary, Model

@final
class MixedBoundaryElasticityResult:
    @property
    def model_digest(self) -> str: ...
    @property
    def semantic_revision(self) -> int: ...
    @property
    def realization_digest(self) -> str: ...
    @property
    def realization_revision(self) -> int: ...
    @property
    def run_digest(self) -> str: ...
    @property
    def run_manifest_json(self) -> bytes: ...
    @property
    def cells_per_axis(self) -> int: ...
    @property
    def bounds(self) -> tuple[tuple[float, float], tuple[float, float]]: ...
    @property
    def displacement_dimension(self) -> tuple[int, int, int, int, int, int, int]: ...
    @property
    def coordinates(self) -> npt.NDArray[np.float64]: ...
    @property
    def cells(self) -> npt.NDArray[np.uint32]: ...
    @property
    def displacement(self) -> npt.NDArray[np.float64]: ...
    @property
    def constrained_reaction(self) -> tuple[float, float]: ...
    @property
    def integrated_body_force(self) -> tuple[float, float]: ...
    @property
    def assembly_packets(self) -> int: ...
    @property
    def assembly_targets(self) -> int: ...
    @property
    def solve(self) -> LinearSolveSummary: ...
    @property
    def case_id(self) -> str: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...

def solve_mixed_boundary_elasticity(
    model: Model,
    /,
) -> MixedBoundaryElasticityResult: ...

__all__ = [
    "MixedBoundaryElasticityResult",
    "solve_mixed_boundary_elasticity",
]
