"""Closed algebraic solve policies.

Authority: ``crates/eqiora-python/src/common_plan.rs::PyLinear``.
"""

from typing import Self, final

@final
class Linear:
    """Admitted host-serial reproducible CG solve policy.

    Authority: ``crates/eqiora-python/src/common_plan.rs::PyLinear``.
    """

    def __new__(cls) -> Self: ...
    @property
    def algorithm(self) -> str: ...
    @property
    def preconditioner(self) -> str: ...
    @property
    def reduction(self) -> str: ...
    @property
    def relative_tolerance(self) -> float: ...
    @property
    def absolute_tolerance(self) -> float: ...
    @property
    def maximum_iterations(self) -> int: ...
    def __eq__(self, other: object, /) -> bool: ...
    def __hash__(self) -> int: ...
    def __repr__(self) -> str: ...

__all__ = ["Linear"]
