from . import DifferentiableProgram

import torch

class TorchProgram:
    def __init__(self, program: DifferentiableProgram) -> None: ...
    @property
    def program(self) -> DifferentiableProgram: ...
    @property
    def input_shape(self) -> tuple[int]: ...
    @property
    def output_shape(self) -> tuple[int]: ...
    def __call__(self, parameters: torch.Tensor) -> torch.Tensor: ...

def bind(program: DifferentiableProgram) -> TorchProgram: ...

__all__ = ["TorchProgram", "bind"]
