# Generated by Eqiora Studio from an accepted authored CAD graph.
# Length arguments are coherent-SI metres.
import eqiora

authored_graph = eqiora.geometry.CadAuthoredGraph.rectangle_extrusion(
    x_bounds=(-2.0, 3.0),
    y_bounds=(-1.0, 2.0),
    plane_z=0.5,
    depth=4.0,
    modeling_tolerance=1e-9,
)

_expected_graph_digest = (
    "919545f70118840c04da9715829deb2da947460a51311ebabec6a34038c66f36"
)
if authored_graph.graph_digest != _expected_graph_digest:
    raise RuntimeError("Eqiora authored CAD graph digest mismatch after reconstruction")
