import type { CommandDefinition, WorkflowDefinition } from "./application";

const ALL = ["relations", "packaged-dc-drive", "cad-box", "cad-authored"] as const;
export const COMMAND_REGISTRY = [
  {
    id: "model.compile",
    group: "model",
    label: "command.model.compile.label",
    description: "command.model.compile.description",
    shortcut: "Ctrl/⌘ Enter",
    focusTarget: null,
    workflows: ALL,
  },
  {
    id: "edit.commit",
    group: "model",
    label: "command.edit.commit.label",
    description: "command.edit.commit.description",
    shortcut: null,
    focusTarget: null,
    workflows: ["relations"],
  },
  {
    id: "history.undo",
    group: "model",
    label: "command.history.undo.label",
    description: "command.history.undo.description",
    shortcut: "Ctrl/⌘ Z",
    focusTarget: null,
    workflows: ALL,
  },
  {
    id: "history.redo",
    group: "model",
    label: "command.history.redo.label",
    description: "command.history.redo.description",
    shortcut: "Ctrl/⌘ ⇧ Z",
    focusTarget: null,
    workflows: ALL,
  },
  {
    id: "view.reflow",
    group: "view",
    label: "command.view.reflow.label",
    description: "command.view.reflow.description",
    shortcut: null,
    focusTarget: null,
    workflows: ["relations"],
  },
  {
    id: "workspace.relations",
    group: "view",
    label: "command.workspace.relations.label",
    description: "command.workspace.relations.description",
    shortcut: null,
    focusTarget: "relation-view",
    workflows: ALL,
  },
  {
    id: "workspace.trajectory",
    group: "view",
    label: "command.workspace.trajectory.label",
    description: "command.workspace.trajectory.description",
    shortcut: null,
    focusTarget: "trajectory-viewport",
    workflows: ALL,
  },
  {
    id: "workspace.geometry",
    group: "view",
    label: "command.workspace.geometry.label",
    description: "command.workspace.geometry.description",
    shortcut: null,
    focusTarget: "cad-viewport",
    workflows: ALL,
  },
  {
    id: "workspace.cad-authoring",
    group: "view",
    label: "command.workspace.cad-authoring.label",
    description: "command.workspace.cad-authoring.description",
    shortcut: null,
    focusTarget: "cad-authored-workspace",
    workflows: ALL,
  },
  {
    id: "example.dc-drive",
    group: "model",
    label: "command.example.dc-drive.label",
    description: "command.example.dc-drive.description",
    shortcut: null,
    focusTarget: null,
    workflows: ALL,
  },
  {
    id: "example.cad",
    group: "model",
    label: "command.example.cad.label",
    description: "command.example.cad.description",
    shortcut: null,
    focusTarget: null,
    workflows: ALL,
  },
  {
    id: "focus.source",
    group: "navigate",
    label: "command.focus.source.label",
    description: "command.focus.source.description",
    shortcut: null,
    focusTarget: "source-editor",
    workflows: ["relations"],
  },
  {
    id: "focus.relation",
    group: "navigate",
    label: "command.focus.relation.label",
    description: "command.focus.relation.description",
    shortcut: null,
    focusTarget: "relation-view",
    workflows: ["relations"],
  },
  {
    id: "focus.inspector",
    group: "navigate",
    label: "command.focus.inspector.label",
    description: "command.focus.inspector.description",
    shortcut: null,
    focusTarget: "selection-inspector",
    workflows: ALL,
  },
  {
    id: "focus.evidence",
    group: "navigate",
    label: "command.focus.evidence.label",
    description: "command.focus.evidence.description",
    shortcut: null,
    focusTarget: "evidence-inspector",
    workflows: ["packaged-dc-drive"],
  },
] as const satisfies readonly CommandDefinition[];
export const WORKFLOW_REGISTRY = [
  {
    id: "relations",
    workspace: "relations",
    label: "workflow.relations.label",
    description: "workflow.relations.description",
    primaryFocus: "relation-view",
  },
  {
    id: "packaged-dc-drive",
    workspace: "trajectory",
    label: "workflow.dc-drive.label",
    description: "workflow.dc-drive.description",
    primaryFocus: "trajectory-viewport",
  },
  {
    id: "cad-box",
    workspace: "geometry",
    label: "workflow.cad.label",
    description: "workflow.cad.description",
    primaryFocus: "cad-viewport",
  },
  {
    id: "cad-authored",
    workspace: "cad-authoring",
    label: "workflow.cad-authored.label",
    description: "workflow.cad-authored.description",
    primaryFocus: "cad-authored-workspace",
  },
] as const satisfies readonly WorkflowDefinition[];
