from __future__ import annotations

import importlib.util
import json
import sys
import tempfile
import unittest
from pathlib import Path

TOOLS = Path(__file__).resolve().parents[1]


def load_module(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


catalog = load_module("generate_evidence_catalog", TOOLS / "generate_evidence_catalog.py")
site_check = load_module("check_site", TOOLS / "check_site.py")


def index(entries):
    return {
        "schema": "eqiora.capability-evidence-index/v3",
        "selected_capability": None,
        "success": True,
        "entries": entries,
        "errors": [],
    }


def entry(capability="spatial.solve", case="numerics.example", manifest=None):
    return {
        "capability": capability,
        "case": case,
        "manifest": manifest or f"verify/numerics/{case}/case.toml",
        "status": "verified",
        "reference_kind": "independent-analytic",
        "conformance_kits": ["linear-v1"],
        "evidence": {
            "package": "eqiora-numerics",
            "test": "example",
            "features": ["evidence-runtime"],
        },
    }


class EvidenceCatalogTests(unittest.TestCase):
    BANNER = (
        "{/* Generated by tools/site/generate_evidence_catalog.py; do not edit. */}"
    )

    @staticmethod
    def invoke_check(document, output):
        from contextlib import redirect_stderr
        from io import StringIO

        input_path = output.parent / "evidence-index.json"
        input_path.write_text(json.dumps(document), encoding="utf-8")
        with redirect_stderr(StringIO()):
            try:
                return catalog.main(
                    ["--check", "--input", str(input_path), "--output", str(output)]
                )
            except SystemExit as error:
                return int(error.code)

    def test_00_complete_canonical_projection_passes_first_and_is_stable(self):
        canonical = index(
            [
                entry("a.capability", "case-a", "verify/numerics/case-a/case.toml"),
                entry("a.capability", "case-z", "verify/numerics/case-z/case.toml"),
            ]
        )
        first = catalog.render_catalog(canonical)
        second = catalog.render_catalog(json.loads(json.dumps(canonical)))
        self.assertEqual(first, second)
        self.assertTrue(first.endswith("\n"))
        self.assertFalse(first.endswith("\n\n"))
        self.assertNotIn("\r", first)
        self.assertEqual(first.count(self.BANNER), 1)
        self.assertLess(
            first.index(
                "import ExactSourceLink from '@components/site/ExactSourceLink.astro';"
            ),
            first.index(self.BANNER),
        )
        self.assertLess(first.index(self.BANNER), first.index("# Evidence catalog"))
        self.assertLess(first.index("case-a"), first.index("case-z"))
        self.assertIn(
            '<ExactSourceLink path="verify/numerics/case-a/case.toml" kind="blob">',
            first,
        )
        self.assertNotIn("/main/", first)
        self.assertNotIn("https://github.com", first)

        with tempfile.TemporaryDirectory() as temporary:
            output = Path(temporary) / "index.mdx"
            output.write_text(first, encoding="utf-8")
            self.assertEqual(self.invoke_check(canonical, output), 0)
            self.assertEqual(output.read_text(encoding="utf-8"), first)

    def test_reversed_noncanonical_order_is_rejected(self):
        canonical = index(
            [
                entry("a.capability", "case-a", "verify/numerics/case-a/case.toml"),
                entry("a.capability", "case-z", "verify/numerics/case-z/case.toml"),
            ]
        )
        reversed_entries = index(list(reversed(canonical["entries"])))
        with self.assertRaises(catalog.CatalogError):
            catalog.render_catalog(reversed_entries)

    def test_canonical_retarget_fails_check_without_writing(self):
        canonical = index(
            [
                entry("a.capability", "case-a", "verify/numerics/case-a/case.toml"),
                entry("a.capability", "case-z", "verify/numerics/case-z/case.toml"),
            ]
        )
        retargeted = json.loads(json.dumps(canonical))
        retargeted["entries"][0] = entry(
            "a.capability", "case-b", "verify/numerics/case-b/case.toml"
        )
        with tempfile.TemporaryDirectory() as temporary:
            output = Path(temporary) / "index.mdx"
            original = catalog.render_catalog(canonical)
            output.write_text(original, encoding="utf-8")
            self.assertEqual(self.invoke_check(canonical, output), 0)
            self.assertNotEqual(self.invoke_check(retargeted, output), 0)
            self.assertEqual(output.read_text(encoding="utf-8"), original)

    def test_exact_banner_and_stale_output_variants_fail_without_writing(self):
        canonical = index([entry()])
        rendered = catalog.render_catalog(canonical)
        with tempfile.TemporaryDirectory() as temporary:
            output = Path(temporary) / "index.mdx"
            output.write_text(rendered, encoding="utf-8")
            self.assertEqual(self.invoke_check(canonical, output), 0)
        variants = {
            "missing banner": rendered.replace(self.BANNER, ""),
            "duplicate banner": rendered.replace(
                self.BANNER, f"{self.BANNER}\n{self.BANNER}"
            ),
            "moved banner": rendered.replace(self.BANNER, "") + self.BANNER + "\n",
            "HTML banner": rendered.replace(
                self.BANNER,
                "<!-- Generated by tools/site/generate_evidence_catalog.py; do not edit. -->",
            ),
            "visible banner": rendered.replace(
                self.BANNER,
                "Generated by tools/site/generate_evidence_catalog.py; do not edit.",
            ),
            "changed banner": rendered.replace("do not edit", "generated file"),
            "missing final LF": rendered.removesuffix("\n"),
            "stale entry": rendered.replace("numerics.example", "numerics.stale"),
        }
        for label, variant in variants.items():
            with self.subTest(label=label), tempfile.TemporaryDirectory() as temporary:
                output = Path(temporary) / "index.mdx"
                output.write_text(variant, encoding="utf-8", newline="")
                before = output.read_bytes()
                self.assertNotEqual(self.invoke_check(canonical, output), 0)
                self.assertEqual(output.read_bytes(), before)

    def test_missing_input_entry_is_stale_not_a_smaller_complete_projection(self):
        complete = index(
            [
                entry("a.capability", "case-a", "verify/numerics/case-a/case.toml"),
                entry("a.capability", "case-z", "verify/numerics/case-z/case.toml"),
            ]
        )
        missing = index(complete["entries"][:-1])
        with tempfile.TemporaryDirectory() as temporary:
            output = Path(temporary) / "index.mdx"
            tracked = catalog.render_catalog(complete)
            output.write_text(tracked, encoding="utf-8")
            self.assertEqual(self.invoke_check(complete, output), 0)
            self.assertNotEqual(self.invoke_check(missing, output), 0)
            self.assertEqual(output.read_text(encoding="utf-8"), tracked)

    def test_failed_or_filtered_index_is_rejected(self):
        failed = index([])
        failed["success"] = False
        with self.assertRaises(catalog.CatalogError):
            catalog.render_catalog(failed)
        errors = index([])
        errors["errors"] = ["producer failure"]
        with self.assertRaises(catalog.CatalogError):
            catalog.render_catalog(errors)
        filtered = index([])
        filtered["selected_capability"] = "one"
        with self.assertRaises(catalog.CatalogError):
            catalog.render_catalog(filtered)

    def test_duplicate_identity_and_escaping_manifest_are_rejected(self):
        duplicate = entry()
        with self.assertRaises(catalog.CatalogError):
            catalog.render_catalog(index([duplicate, duplicate]))
        escaping = entry()
        escaping["manifest"] = "../case.toml"
        with self.assertRaises(catalog.CatalogError):
            catalog.render_catalog(index([escaping]))

        unknown = entry()
        unknown["unexpected"] = True
        with self.assertRaises(catalog.CatalogError):
            catalog.render_catalog(index([unknown]))

        status = entry()
        status["status"] = "production-ready"
        with self.assertRaises(catalog.CatalogError):
            catalog.render_catalog(index([status]))

    def test_physical_environment_is_visible_and_closed(self):
        physical = entry()
        physical["evidence"]["environment"] = "physical-mpi-cuda"
        rendered = catalog.render_catalog(index([physical]))
        self.assertIn("environment: physical-mpi-cuda", rendered)

        physical["evidence"]["environment"] = "unreviewed-runner"
        with self.assertRaises(catalog.CatalogError):
            catalog.render_catalog(index([physical]))

    def test_cargo_library_target_is_visible_and_closed(self):
        library = entry()
        library["evidence"] = {
            "runner": "cargo-library-test",
            "package": "eqiora-api",
            "test": "parameter_study::tests::registered_evidence",
        }
        rendered = catalog.render_catalog(index([library]))
        self.assertIn(
            "cargo-library-test: eqiora-api/parameter_study::tests::registered_evidence",
            rendered,
        )

        library["evidence"]["runner"] = "unreviewed-runner"
        with self.assertRaises(catalog.CatalogError):
            catalog.render_catalog(index([library]))


class SiteCheckTests(unittest.TestCase):
    def test_local_link_checker_accepts_existing_and_rejects_escape(self):
        with tempfile.TemporaryDirectory() as temporary:
            site = Path(temporary) / "docs/site"
            site.mkdir(parents=True)
            (site / "target.md").write_text("# Target\n", encoding="utf-8")
            source = site / "index.md"
            source.write_text("[Target](target.md)\n", encoding="utf-8")
            self.assertEqual(site_check.check_markdown_links(site), [])
            source.write_text("[Private](../../secret.md)\n", encoding="utf-8")
            errors = site_check.check_markdown_links(site)
            self.assertTrue(any("escapes docs/site" in error for error in errors))

    def test_action_regex_requires_full_sha(self):
        pinned = "uses: actions/checkout@" + "a" * 40
        floating = "uses: actions/checkout@v7"
        self.assertEqual(site_check.ACTION_USE.findall(pinned)[0][1], "a" * 40)
        self.assertNotRegex(site_check.ACTION_USE.findall(floating)[0][1], r"^[0-9a-f]{40}$")


if __name__ == "__main__":
    unittest.main()
