from __future__ import annotations

import importlib.util
import json
import subprocess
import sys
import tempfile
import unittest
from html import unescape
from pathlib import Path

TOOLS = Path(__file__).resolve().parents[1]


def load_module(name: str, path: Path):
    spec = importlib.util.spec_from_file_location(name, path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    sys.modules[name] = module
    spec.loader.exec_module(module)
    return module


catalog = load_module("generate_evidence_catalog", TOOLS / "generate_evidence_catalog.py")
site_check = load_module("check_site", TOOLS / "check_site.py")


def index(entries):
    return {
        "schema": "eqiora.capability-evidence-index/v3",
        "selected_capability": None,
        "success": True,
        "entries": entries,
        "errors": [],
    }


def entry(capability="spatial.solve", case="numerics.example", manifest=None):
    area, name = case.split(".", 1)
    return {
        "capability": capability,
        "case": case,
        "manifest": manifest or f"verify/{area}/{name}/case.toml",
        "status": "verified",
        "reference_kind": "independent-analytic",
        "conformance_kits": ["linear-v1"],
        "evidence": {
            "package": "eqiora-numerics",
            "test": "example",
            "features": ["evidence-runtime"],
        },
    }


class EvidenceCatalogTests(unittest.TestCase):
    BANNER = (
        "{/* Generated by tools/site/generate_evidence_catalog.py; do not edit. */}"
    )

    @staticmethod
    def invoke_check(document, output):
        from contextlib import redirect_stderr
        from io import StringIO

        input_path = output.parent / "evidence-index.json"
        input_path.write_text(json.dumps(document), encoding="utf-8")
        with redirect_stderr(StringIO()):
            try:
                return catalog.main(
                    ["--check", "--input", str(input_path), "--output", str(output)]
                )
            except SystemExit as error:
                return int(error.code)

    @staticmethod
    def render_reference_entry(document):
        rendered = catalog.render_catalog(document)
        lines = rendered.splitlines()
        start = next(
            offset
            for offset, line in enumerate(lines)
            if line == "<dt>Capability</dt><dd>spatial.solve</dd>"
        )
        source = "<dl>\n" + "\n".join(lines[start : start + 6]) + "\n</dl>\n"
        script = """
import { markdownToHtml } from 'satteri';
import { katexMathPlugin } from './src/plugins/katex.ts';
let source = '';
process.stdin.setEncoding('utf8');
for await (const chunk of process.stdin) source += chunk;
const { html } = markdownToHtml(source, {
  features: { math: true },
  mdastPlugins: [katexMathPlugin],
});
process.stdout.write(html);
"""
        return subprocess.run(
            ["node", "--input-type=module", "--eval", script],
            cwd=TOOLS.parents[1] / "docs/site",
            input=source,
            text=True,
            capture_output=True,
            check=True,
        ).stdout

    def test_00_complete_canonical_projection_passes_first_and_is_stable(self):
        canonical = index(
            [
                entry("a.capability", "numerics.case-a"),
                entry("a.capability", "numerics.case-z"),
            ]
        )
        first = catalog.render_catalog(canonical)
        second = catalog.render_catalog(json.loads(json.dumps(canonical)))
        self.assertEqual(first, second)
        self.assertTrue(first.endswith("\n"))
        self.assertFalse(first.endswith("\n\n"))
        self.assertNotIn("\r", first)
        self.assertEqual(first.count(self.BANNER), 1)
        self.assertLess(
            first.index(
                "import ExactSourceLink from '@components/site/ExactSourceLink.astro';"
            ),
            first.index(self.BANNER),
        )
        self.assertTrue(
            first.startswith(
                "---\n"
                "title: Evidence catalog\n"
                "description: Exact capability-to-case projection; manifests remain authoritative.\n"
                "---\n\n"
                "import ExactSourceLink from '@components/site/ExactSourceLink.astro';\n\n"
                f"{self.BANNER}\n\n"
            )
        )
        self.assertLess(first.index("case-a"), first.index("case-z"))
        self.assertIn(
            '<ExactSourceLink path={"verify/numerics/case-a/case.toml"} '
            'kind="blob"><code>numerics.case-a</code></ExactSourceLink>',
            first,
        )
        self.assertNotIn("/main/", first)
        self.assertNotIn("https://github.com", first)
        self.assertEqual(first.count("<details>"), 1)
        self.assertEqual(first.count("</details>"), 1)
        self.assertIn(
            "<summary><code>numerics</code> — 2 entries</summary>", first
        )
        entries = [
            line
            for line in first.splitlines()
            if line == "<dt>Capability</dt><dd>a.capability</dd>"
        ]
        self.assertEqual(len(entries), len(canonical["entries"]))
        self.assertNotIn("| Capability | Case |", first)
        self.assertEqual(first.count("<ol>"), 1)
        self.assertEqual(first.count("<dl>"), len(canonical["entries"]))

        with tempfile.TemporaryDirectory() as temporary:
            output = Path(temporary) / "index.mdx"
            output.write_text(first, encoding="utf-8")
            self.assertEqual(self.invoke_check(canonical, output), 0)
            self.assertEqual(output.read_text(encoding="utf-8"), first)

    def test_01_reference_metacharacters_remain_literal_through_site_processor(self):
        ordinary_html = self.render_reference_entry(index([entry()]))
        self.assertIn("<dd>independent-analytic</dd>", ordinary_html)
        self.assertNotIn("<em", ordinary_html)
        self.assertNotIn("<math", ordinary_html)
        self.assertNotIn('class="katex"', ordinary_html)

        metacharacters = entry()
        metacharacters["reference_kind"] = "_em_ $x$"
        rendered_html = self.render_reference_entry(index([metacharacters]))
        self.assertIn("<dd>_em_ $x$</dd>", unescape(rendered_html))
        self.assertNotIn("<em", rendered_html)
        self.assertNotIn("<math", rendered_html)
        self.assertNotIn('class="katex"', rendered_html)

    def test_reversed_noncanonical_order_is_rejected(self):
        canonical = index(
            [
                entry("a.capability", "numerics.case-a"),
                entry("a.capability", "numerics.case-z"),
            ]
        )
        reversed_entries = index(list(reversed(canonical["entries"])))
        with self.assertRaises(catalog.CatalogError):
            catalog.render_catalog(reversed_entries)

    def test_canonical_retarget_fails_check_without_writing(self):
        canonical = index(
            [
                entry("a.capability", "numerics.case-a"),
                entry("a.capability", "numerics.case-z"),
            ]
        )
        retargeted = json.loads(json.dumps(canonical))
        retargeted["entries"][0]["manifest"] = "verify/numerics/case-b/case.toml"
        with tempfile.TemporaryDirectory() as temporary:
            output = Path(temporary) / "index.mdx"
            original = catalog.render_catalog(canonical)
            output.write_text(original, encoding="utf-8")
            self.assertEqual(self.invoke_check(canonical, output), 0)
            self.assertNotEqual(self.invoke_check(retargeted, output), 0)
            self.assertEqual(output.read_text(encoding="utf-8"), original)

    def test_exact_banner_and_stale_output_variants_fail_without_writing(self):
        canonical = index([entry()])
        rendered = catalog.render_catalog(canonical)
        with tempfile.TemporaryDirectory() as temporary:
            output = Path(temporary) / "index.mdx"
            output.write_text(rendered, encoding="utf-8")
            self.assertEqual(self.invoke_check(canonical, output), 0)
        variants = {
            "missing banner": rendered.replace(self.BANNER, ""),
            "duplicate banner": rendered.replace(
                self.BANNER, f"{self.BANNER}\n{self.BANNER}"
            ),
            "moved banner": rendered.replace(self.BANNER, "") + self.BANNER + "\n",
            "HTML banner": rendered.replace(
                self.BANNER,
                "<!-- Generated by tools/site/generate_evidence_catalog.py; do not edit. -->",
            ),
            "visible banner": rendered.replace(
                self.BANNER,
                "Generated by tools/site/generate_evidence_catalog.py; do not edit.",
            ),
            "changed banner": rendered.replace("do not edit", "generated file"),
            "missing final LF": rendered.removesuffix("\n"),
            "stale entry": rendered.replace("numerics.example", "numerics.stale"),
        }
        for label, variant in variants.items():
            with self.subTest(label=label), tempfile.TemporaryDirectory() as temporary:
                output = Path(temporary) / "index.mdx"
                output.write_text(variant, encoding="utf-8", newline="")
                before = output.read_bytes()
                self.assertNotEqual(self.invoke_check(canonical, output), 0)
                self.assertEqual(output.read_bytes(), before)

    def test_missing_input_entry_is_stale_not_a_smaller_complete_projection(self):
        complete = index(
            [
                entry("a.capability", "numerics.case-a"),
                entry("a.capability", "numerics.case-z"),
            ]
        )
        missing = index(complete["entries"][:-1])
        with tempfile.TemporaryDirectory() as temporary:
            output = Path(temporary) / "index.mdx"
            tracked = catalog.render_catalog(complete)
            output.write_text(tracked, encoding="utf-8")
            self.assertEqual(self.invoke_check(complete, output), 0)
            self.assertNotEqual(self.invoke_check(missing, output), 0)
            self.assertEqual(output.read_text(encoding="utf-8"), tracked)

    def test_failed_or_filtered_index_is_rejected(self):
        failed = index([])
        failed["success"] = False
        with self.assertRaises(catalog.CatalogError):
            catalog.render_catalog(failed)
        errors = index([])
        errors["errors"] = ["producer failure"]
        with self.assertRaises(catalog.CatalogError):
            catalog.render_catalog(errors)
        filtered = index([])
        filtered["selected_capability"] = "one"
        with self.assertRaises(catalog.CatalogError):
            catalog.render_catalog(filtered)

    def test_duplicate_identity_and_escaping_manifest_are_rejected(self):
        duplicate = entry()
        with self.assertRaises(catalog.CatalogError):
            catalog.render_catalog(index([duplicate, duplicate]))
        escaping = entry()
        escaping["manifest"] = "../case.toml"
        with self.assertRaises(catalog.CatalogError):
            catalog.render_catalog(index([escaping]))

        unknown = entry()
        unknown["unexpected"] = True
        with self.assertRaises(catalog.CatalogError):
            catalog.render_catalog(index([unknown]))

        status = entry()
        status["status"] = "production-ready"
        with self.assertRaises(catalog.CatalogError):
            catalog.render_catalog(index([status]))

    def test_physical_environment_is_visible_and_closed(self):
        physical = entry()
        physical["evidence"]["environment"] = "physical-mpi-cuda"
        rendered = catalog.render_catalog(index([physical]))
        self.assertIn("environment: physical-mpi-cuda", rendered)

        physical["evidence"]["environment"] = "unreviewed-runner"
        with self.assertRaises(catalog.CatalogError):
            catalog.render_catalog(index([physical]))

    def test_area_summary_counts_statuses_environments_and_links_representative(self):
        entries = [
            entry("a.proposed", "fluid.case-a"),
            entry("b.verified", "fluid.case-z"),
            entry("c.implemented", "numerics.case-a"),
        ]
        entries[0]["status"] = "proposed"
        entries[0]["evidence"] = None
        entries[1]["evidence"]["environment"] = "physical-mpi-cuda"
        entries[2]["status"] = "implemented"
        rendered = catalog.render_catalog(index(entries))

        self.assertIn(
            '| `fluid` | 1 | 0 | 0 | 1 | 0 | physical-mpi-cuda | '
            '<ExactSourceLink path={"verify/fluid/case-a/case.toml"} '
            'kind="blob"><code>fluid.case-a</code></ExactSourceLink> |',
            rendered,
        )
        self.assertIn(
            '| `numerics` | 0 | 0 | 1 | 0 | 0 | host-cpu |', rendered
        )
        self.assertIn(
            "Statuses below verified are not verification. A claim's scope is exactly "
            "its entry, nothing broader. Environment-specific evidence does not "
            "generalize to another environment.",
            rendered,
        )
        self.assertLess(rendered.index("`fluid`"), rendered.index("`numerics`"))
        self.assertEqual(rendered.count("<details>"), 2)
        self.assertEqual(rendered.count("<ol>"), 2)
        self.assertEqual(rendered.count("<dl>"), len(entries))

    def test_cargo_library_target_is_visible_and_closed(self):
        library = entry()
        library["evidence"] = {
            "runner": "cargo-library-test",
            "package": "eqiora-api",
            "test": "parameter_study::tests::registered_evidence",
        }
        rendered = catalog.render_catalog(index([library]))
        self.assertIn(
            "cargo-library-test: eqiora-api/parameter_study::tests::registered_evidence",
            rendered,
        )

        library["evidence"]["runner"] = "unreviewed-runner"
        with self.assertRaises(catalog.CatalogError):
            catalog.render_catalog(index([library]))


class SiteCheckTests(unittest.TestCase):
    def test_local_link_checker_accepts_existing_and_rejects_escape(self):
        with tempfile.TemporaryDirectory() as temporary:
            site = Path(temporary) / "docs/site"
            site.mkdir(parents=True)
            (site / "target.md").write_text("# Target\n", encoding="utf-8")
            source = site / "index.md"
            source.write_text("[Target](target.md)\n", encoding="utf-8")
            self.assertEqual(site_check.check_markdown_links(site), [])
            source.write_text("[Private](../../secret.md)\n", encoding="utf-8")
            errors = site_check.check_markdown_links(site)
            self.assertTrue(any("escapes docs/site" in error for error in errors))

    def test_action_regex_requires_full_sha(self):
        pinned = "uses: actions/checkout@" + "a" * 40
        floating = "uses: actions/checkout@v7"
        self.assertEqual(site_check.ACTION_USE.findall(pinned)[0][1], "a" * 40)
        self.assertNotRegex(site_check.ACTION_USE.findall(floating)[0][1], r"^[0-9a-f]{40}$")


if __name__ == "__main__":
    unittest.main()
